# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1153, 663)
        MainWindow.setStyleSheet("url:(/newPrefix/Logo-Uni-Tor-Vergata.png_48x48.png)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Immagine_tor_Vergata_Grande = QtWidgets.QLabel(self.centralwidget)
        self.Immagine_tor_Vergata_Grande.setGeometry(QtCore.QRect(850, 60, 111, 131))
        self.Immagine_tor_Vergata_Grande.setStyleSheet("image: url(:/newPrefix/Logo-Uni-Tor-Vergata.jpg);")
        self.Immagine_tor_Vergata_Grande.setText("")
        self.Immagine_tor_Vergata_Grande.setObjectName("Immagine_tor_Vergata_Grande")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(120, 50, 841, 351))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.basics = QtWidgets.QWidget()
        self.basics.setObjectName("basics")
        self.pushButton_2 = QtWidgets.QPushButton(self.basics)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 140, 121, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.Passi_encoder_scritta = QtWidgets.QLabel(self.basics)
        self.Passi_encoder_scritta.setGeometry(QtCore.QRect(130, 30, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Passi_encoder_scritta.setFont(font)
        self.Passi_encoder_scritta.setObjectName("Passi_encoder_scritta")
        self.layoutWidget = QtWidgets.QWidget(self.basics)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 60, 351, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Motore1 = QtWidgets.QHBoxLayout()
        self.Motore1.setObjectName("Motore1")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.Motore1.addWidget(self.label_3)
        self.riferimento1 = QtWidgets.QSpinBox(self.layoutWidget)
        self.riferimento1.setObjectName("riferimento1")
        self.Motore1.addWidget(self.riferimento1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.Motore1.addWidget(self.label_4)
        self.passi1 = QtWidgets.QLabel(self.layoutWidget)
        self.passi1.setObjectName("passi1")
        self.Motore1.addWidget(self.passi1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.Motore1.addWidget(self.label_5)
        self.flow1 = QtWidgets.QLabel(self.layoutWidget)
        self.flow1.setObjectName("flow1")
        self.Motore1.addWidget(self.flow1)
        self.verticalLayout.addLayout(self.Motore1)
        self.Motore2 = QtWidgets.QHBoxLayout()
        self.Motore2.setObjectName("Motore2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.Motore2.addWidget(self.label_6)
        self.riferimento1_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.riferimento1_2.setObjectName("riferimento1_2")
        self.Motore2.addWidget(self.riferimento1_2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.Motore2.addWidget(self.label_7)
        self.passi1_2 = QtWidgets.QLabel(self.layoutWidget)
        self.passi1_2.setObjectName("passi1_2")
        self.Motore2.addWidget(self.passi1_2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.Motore2.addWidget(self.label_8)
        self.flow1_2 = QtWidgets.QLabel(self.layoutWidget)
        self.flow1_2.setObjectName("flow1_2")
        self.Motore2.addWidget(self.flow1_2)
        self.verticalLayout.addLayout(self.Motore2)
        self.Motore3 = QtWidgets.QHBoxLayout()
        self.Motore3.setObjectName("Motore3")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.Motore3.addWidget(self.label_9)
        self.riferimento1_3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.riferimento1_3.setObjectName("riferimento1_3")
        self.Motore3.addWidget(self.riferimento1_3)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.Motore3.addWidget(self.label_10)
        self.passi1_3 = QtWidgets.QLabel(self.layoutWidget)
        self.passi1_3.setObjectName("passi1_3")
        self.Motore3.addWidget(self.passi1_3)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.Motore3.addWidget(self.label_11)
        self.flow1_3 = QtWidgets.QLabel(self.layoutWidget)
        self.flow1_3.setObjectName("flow1_3")
        self.Motore3.addWidget(self.flow1_3)
        self.verticalLayout.addLayout(self.Motore3)
        self.Motore4 = QtWidgets.QHBoxLayout()
        self.Motore4.setObjectName("Motore4")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.Motore4.addWidget(self.label_12)
        self.riferimento1_4 = QtWidgets.QSpinBox(self.layoutWidget)
        self.riferimento1_4.setObjectName("riferimento1_4")
        self.Motore4.addWidget(self.riferimento1_4)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.Motore4.addWidget(self.label_13)
        self.passi1_4 = QtWidgets.QLabel(self.layoutWidget)
        self.passi1_4.setObjectName("passi1_4")
        self.Motore4.addWidget(self.passi1_4)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.Motore4.addWidget(self.label_14)
        self.flow1_4 = QtWidgets.QLabel(self.layoutWidget)
        self.flow1_4.setObjectName("flow1_4")
        self.Motore4.addWidget(self.flow1_4)
        self.verticalLayout.addLayout(self.Motore4)
        self.Motore5 = QtWidgets.QHBoxLayout()
        self.Motore5.setObjectName("Motore5")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.Motore5.addWidget(self.label_15)
        self.riferimento1_5 = QtWidgets.QSpinBox(self.layoutWidget)
        self.riferimento1_5.setObjectName("riferimento1_5")
        self.Motore5.addWidget(self.riferimento1_5)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.Motore5.addWidget(self.label_16)
        self.passi1_5 = QtWidgets.QLabel(self.layoutWidget)
        self.passi1_5.setObjectName("passi1_5")
        self.Motore5.addWidget(self.passi1_5)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.Motore5.addWidget(self.label_17)
        self.flow1_5 = QtWidgets.QLabel(self.layoutWidget)
        self.flow1_5.setObjectName("flow1_5")
        self.Motore5.addWidget(self.flow1_5)
        self.verticalLayout.addLayout(self.Motore5)
        self.Motore6 = QtWidgets.QHBoxLayout()
        self.Motore6.setObjectName("Motore6")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.Motore6.addWidget(self.label_18)
        self.riferimento1_6 = QtWidgets.QSpinBox(self.layoutWidget)
        self.riferimento1_6.setObjectName("riferimento1_6")
        self.Motore6.addWidget(self.riferimento1_6)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.Motore6.addWidget(self.label_19)
        self.passi1_6 = QtWidgets.QLabel(self.layoutWidget)
        self.passi1_6.setObjectName("passi1_6")
        self.Motore6.addWidget(self.passi1_6)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.Motore6.addWidget(self.label_20)
        self.flow1_6 = QtWidgets.QLabel(self.layoutWidget)
        self.flow1_6.setObjectName("flow1_6")
        self.Motore6.addWidget(self.flow1_6)
        self.verticalLayout.addLayout(self.Motore6)
        self.tabWidget.addTab(self.basics, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_6.setGeometry(QtCore.QRect(30, 60, 351, 241))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Motore1_2 = QtWidgets.QHBoxLayout()
        self.Motore1_2.setObjectName("Motore1_2")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.Motore1_2.addWidget(self.label_21)
        self.riferimento1_7 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.riferimento1_7.setObjectName("riferimento1_7")
        self.Motore1_2.addWidget(self.riferimento1_7)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.Motore1_2.addWidget(self.label_22)
        self.passi1_7 = QtWidgets.QLabel(self.layoutWidget_6)
        self.passi1_7.setObjectName("passi1_7")
        self.Motore1_2.addWidget(self.passi1_7)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.Motore1_2.addWidget(self.label_23)
        self.flow1_7 = QtWidgets.QLabel(self.layoutWidget_6)
        self.flow1_7.setObjectName("flow1_7")
        self.Motore1_2.addWidget(self.flow1_7)
        self.verticalLayout_2.addLayout(self.Motore1_2)
        self.Motore2_2 = QtWidgets.QHBoxLayout()
        self.Motore2_2.setObjectName("Motore2_2")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.Motore2_2.addWidget(self.label_24)
        self.riferimento1_8 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.riferimento1_8.setObjectName("riferimento1_8")
        self.Motore2_2.addWidget(self.riferimento1_8)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.Motore2_2.addWidget(self.label_25)
        self.passi1_8 = QtWidgets.QLabel(self.layoutWidget_6)
        self.passi1_8.setObjectName("passi1_8")
        self.Motore2_2.addWidget(self.passi1_8)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.Motore2_2.addWidget(self.label_26)
        self.flow1_8 = QtWidgets.QLabel(self.layoutWidget_6)
        self.flow1_8.setObjectName("flow1_8")
        self.Motore2_2.addWidget(self.flow1_8)
        self.verticalLayout_2.addLayout(self.Motore2_2)
        self.Motore3_2 = QtWidgets.QHBoxLayout()
        self.Motore3_2.setObjectName("Motore3_2")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.Motore3_2.addWidget(self.label_27)
        self.riferimento1_9 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.riferimento1_9.setObjectName("riferimento1_9")
        self.Motore3_2.addWidget(self.riferimento1_9)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName("label_28")
        self.Motore3_2.addWidget(self.label_28)
        self.passi1_9 = QtWidgets.QLabel(self.layoutWidget_6)
        self.passi1_9.setObjectName("passi1_9")
        self.Motore3_2.addWidget(self.passi1_9)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.Motore3_2.addWidget(self.label_29)
        self.flow1_9 = QtWidgets.QLabel(self.layoutWidget_6)
        self.flow1_9.setObjectName("flow1_9")
        self.Motore3_2.addWidget(self.flow1_9)
        self.verticalLayout_2.addLayout(self.Motore3_2)
        self.Motore4_2 = QtWidgets.QHBoxLayout()
        self.Motore4_2.setObjectName("Motore4_2")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.Motore4_2.addWidget(self.label_30)
        self.riferimento1_10 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.riferimento1_10.setObjectName("riferimento1_10")
        self.Motore4_2.addWidget(self.riferimento1_10)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.Motore4_2.addWidget(self.label_31)
        self.passi1_10 = QtWidgets.QLabel(self.layoutWidget_6)
        self.passi1_10.setObjectName("passi1_10")
        self.Motore4_2.addWidget(self.passi1_10)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName("label_32")
        self.Motore4_2.addWidget(self.label_32)
        self.flow1_10 = QtWidgets.QLabel(self.layoutWidget_6)
        self.flow1_10.setObjectName("flow1_10")
        self.Motore4_2.addWidget(self.flow1_10)
        self.verticalLayout_2.addLayout(self.Motore4_2)
        self.Motore5_2 = QtWidgets.QHBoxLayout()
        self.Motore5_2.setObjectName("Motore5_2")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName("label_33")
        self.Motore5_2.addWidget(self.label_33)
        self.riferimento1_11 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.riferimento1_11.setObjectName("riferimento1_11")
        self.Motore5_2.addWidget(self.riferimento1_11)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName("label_34")
        self.Motore5_2.addWidget(self.label_34)
        self.passi1_11 = QtWidgets.QLabel(self.layoutWidget_6)
        self.passi1_11.setObjectName("passi1_11")
        self.Motore5_2.addWidget(self.passi1_11)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.Motore5_2.addWidget(self.label_35)
        self.flow1_11 = QtWidgets.QLabel(self.layoutWidget_6)
        self.flow1_11.setObjectName("flow1_11")
        self.Motore5_2.addWidget(self.flow1_11)
        self.verticalLayout_2.addLayout(self.Motore5_2)
        self.Motore6_2 = QtWidgets.QHBoxLayout()
        self.Motore6_2.setObjectName("Motore6_2")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.Motore6_2.addWidget(self.label_36)
        self.riferimento1_12 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.riferimento1_12.setObjectName("riferimento1_12")
        self.Motore6_2.addWidget(self.riferimento1_12)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName("label_37")
        self.Motore6_2.addWidget(self.label_37)
        self.passi1_12 = QtWidgets.QLabel(self.layoutWidget_6)
        self.passi1_12.setObjectName("passi1_12")
        self.Motore6_2.addWidget(self.passi1_12)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName("label_38")
        self.Motore6_2.addWidget(self.label_38)
        self.flow1_12 = QtWidgets.QLabel(self.layoutWidget_6)
        self.flow1_12.setObjectName("flow1_12")
        self.Motore6_2.addWidget(self.flow1_12)
        self.verticalLayout_2.addLayout(self.Motore6_2)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.PulsanteInvioPAginaAdvance = QtWidgets.QPushButton(self.tab_2)
        self.PulsanteInvioPAginaAdvance.setGeometry(QtCore.QRect(480, 140, 121, 41))
        self.PulsanteInvioPAginaAdvance.setObjectName("PulsanteInvioPAginaAdvance")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(280, 60, 110, 39))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Gomitoalto = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.Gomitoalto.setObjectName("Gomitoalto")
        self.verticalLayout_3.addWidget(self.Gomitoalto)
        self.Gomitobasso = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.Gomitobasso.setObjectName("Gomitobasso")
        self.verticalLayout_3.addWidget(self.Gomitobasso)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 115, 231))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Xdes = QtWidgets.QLabel(self.layoutWidget_3)
        self.Xdes.setObjectName("Xdes")
        self.horizontalLayout.addWidget(self.Xdes)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout.addWidget(self.doubleSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Ydes = QtWidgets.QLabel(self.layoutWidget_3)
        self.Ydes.setObjectName("Ydes")
        self.horizontalLayout_2.addWidget(self.Ydes)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Zdes = QtWidgets.QLabel(self.layoutWidget_3)
        self.Zdes.setObjectName("Zdes")
        self.horizontalLayout_3.addWidget(self.Zdes)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_4.setGeometry(QtCore.QRect(530, 30, 51, 251))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_4.addWidget(self.label_42)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_4.addWidget(self.label_44)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_48 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_6.addWidget(self.label_48)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_6.addWidget(self.label_45)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_46 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_5.addWidget(self.label_46)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_5.addWidget(self.label_43)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_50 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_8.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_8.addWidget(self.label_51)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_49 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_7.addWidget(self.label_49)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_7.addWidget(self.label_47)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(200, 310, 291, 151))
        self.label.setStyleSheet("url:(/image/Logo-Uni-Tor-Vergata.png_96x96.png)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(940, 50, 121, 141))
        self.image.setStyleSheet("url:(/newPrefix/Logo-Uni-Tor-Vergata.png_48x48.png)")
        self.image.setText("")
        self.image.setObjectName("image")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(990, 40, 131, 151))
        self.label_39.setStyleSheet("image: url(:/image/Logo-Uni-Tor-Vergata.png_96x96.png);")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Immagine_tor_Vergata_Grande.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/Immagini/Logo-Uni-Tor-Vergata.png\"/></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "INVIO"))
        self.Passi_encoder_scritta.setText(_translate("MainWindow", "Passi encoder"))
        self.label_3.setText(_translate("MainWindow", "encoder n°1"))
        self.label_4.setText(_translate("MainWindow", "Step:"))
        self.passi1.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "mA:"))
        self.flow1.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "encoder n°2"))
        self.label_7.setText(_translate("MainWindow", "Step:"))
        self.passi1_2.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "mA:"))
        self.flow1_2.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "encoder n°3"))
        self.label_10.setText(_translate("MainWindow", "Step:"))
        self.passi1_3.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "mA:"))
        self.flow1_3.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "encoder n°4"))
        self.label_13.setText(_translate("MainWindow", "Step:"))
        self.passi1_4.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "mA:"))
        self.flow1_4.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "encoder n°5"))
        self.label_16.setText(_translate("MainWindow", "Step:"))
        self.passi1_5.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "mA:"))
        self.flow1_5.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "encoder n°6"))
        self.label_19.setText(_translate("MainWindow", "Step:"))
        self.passi1_6.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "mA:"))
        self.flow1_6.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.basics), _translate("MainWindow", "Basics"))
        self.label_21.setText(_translate("MainWindow", "θ1:  "))
        self.label_22.setText(_translate("MainWindow", "Step:"))
        self.passi1_7.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "mA:"))
        self.flow1_7.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "θ2:  "))
        self.label_25.setText(_translate("MainWindow", "Step:"))
        self.passi1_8.setText(_translate("MainWindow", "0"))
        self.label_26.setText(_translate("MainWindow", "mA:"))
        self.flow1_8.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "θ3:  "))
        self.label_28.setText(_translate("MainWindow", "Step:"))
        self.passi1_9.setText(_translate("MainWindow", "0"))
        self.label_29.setText(_translate("MainWindow", "mA:"))
        self.flow1_9.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "θ4:  "))
        self.label_31.setText(_translate("MainWindow", "Step:"))
        self.passi1_10.setText(_translate("MainWindow", "0"))
        self.label_32.setText(_translate("MainWindow", "mA:"))
        self.flow1_10.setText(_translate("MainWindow", "0"))
        self.label_33.setText(_translate("MainWindow", "θ5:  "))
        self.label_34.setText(_translate("MainWindow", "Step:"))
        self.passi1_11.setText(_translate("MainWindow", "0"))
        self.label_35.setText(_translate("MainWindow", "mA:"))
        self.flow1_11.setText(_translate("MainWindow", "0"))
        self.label_36.setText(_translate("MainWindow", "θ6:  "))
        self.label_37.setText(_translate("MainWindow", "Step:"))
        self.passi1_12.setText(_translate("MainWindow", "0"))
        self.label_38.setText(_translate("MainWindow", "mA:"))
        self.flow1_12.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "Angoli"))
        self.PulsanteInvioPAginaAdvance.setText(_translate("MainWindow", "INVIO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Advance"))
        self.Gomitoalto.setText(_translate("MainWindow", "Gomito alto"))
        self.Gomitobasso.setText(_translate("MainWindow", "Gomito basso"))
        self.Xdes.setText(_translate("MainWindow", "Xdes:"))
        self.Ydes.setText(_translate("MainWindow", "Ydes:"))
        self.Zdes.setText(_translate("MainWindow", "Zdes:"))
        self.label_42.setText(_translate("MainWindow", "θ1:  "))
        self.label_44.setText(_translate("MainWindow", "0"))
        self.label_48.setText(_translate("MainWindow", "θ3:  "))
        self.label_45.setText(_translate("MainWindow", "0"))
        self.label_46.setText(_translate("MainWindow", "θ2:  "))
        self.label_43.setText(_translate("MainWindow", "0"))
        self.label_50.setText(_translate("MainWindow", "θ5:  "))
        self.label_51.setText(_translate("MainWindow", "0"))
        self.label_49.setText(_translate("MainWindow", "θ4:  "))
        self.label_47.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Inverse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Setup"))


import pd


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
