# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uUiClass.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

import pyUi.ScorbotUI.pyqtLib.logo


class UiClass(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1153, 663)
        MainWindow.setStyleSheet("url:(/newPrefix/Logo-Uni-Tor-Vergata.png_48x48.png)\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(20, 20, 20);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Immagine_tor_Vergata_Grande = QtWidgets.QLabel(self.centralwidget)
        self.Immagine_tor_Vergata_Grande.setGeometry(QtCore.QRect(850, 60, 111, 131))
        self.Immagine_tor_Vergata_Grande.setStyleSheet("image: url(:/newPrefix/Logo-Uni-Tor-Vergata.jpg);")
        self.Immagine_tor_Vergata_Grande.setText("")
        self.Immagine_tor_Vergata_Grande.setObjectName("Immagine_tor_Vergata_Grande")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(120, 50, 851, 361))
        self.tabWidget.setStyleSheet("background-color: rgb(244, 242, 246);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Direct = QtWidgets.QWidget()
        self.Direct.setObjectName("Direct")
        self.Pulsante_invio_pagina_Basics = QtWidgets.QPushButton(self.Direct)
        self.Pulsante_invio_pagina_Basics.setGeometry(QtCore.QRect(530, 130, 121, 41))
        self.Pulsante_invio_pagina_Basics.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0246305, y1:0.602273, x2:1, y2:0, stop:0 rgba(0, 139, 0, 255), stop:0.655172 rgba(255, 255, 255, 255));")
        self.Pulsante_invio_pagina_Basics.setObjectName("Pulsante_invio_pagina_Basics")
        self.Passi_encoder_scritta = QtWidgets.QLabel(self.Direct)
        self.Passi_encoder_scritta.setGeometry(QtCore.QRect(130, 30, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Passi_encoder_scritta.setFont(font)
        self.Passi_encoder_scritta.setObjectName("Passi_encoder_scritta")
        self.layoutWidget = QtWidgets.QWidget(self.Direct)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 60, 351, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Vertical_layout_Direct = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.Vertical_layout_Direct.setContentsMargins(0, 0, 0, 0)
        self.Vertical_layout_Direct.setObjectName("Vertical_layout_Direct")
        self.Motore1 = QtWidgets.QHBoxLayout()
        self.Motore1.setObjectName("Motore1")
        self.Encoder1_direct = QtWidgets.QLabel(self.layoutWidget)
        self.Encoder1_direct.setObjectName("Encoder1_direct")
        self.Motore1.addWidget(self.Encoder1_direct)
        self.riferimento1_direct = QtWidgets.QSpinBox(self.layoutWidget)
        self.riferimento1_direct.setObjectName("riferimento1_direct")
        self.Motore1.addWidget(self.riferimento1_direct)
        self.Step1_direct = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step1_direct.sizePolicy().hasHeightForWidth())
        self.Step1_direct.setSizePolicy(sizePolicy)
        self.Step1_direct.setObjectName("Step1_direct")
        self.Motore1.addWidget(self.Step1_direct)
        self.passi1_direct = QtWidgets.QLabel(self.layoutWidget)
        self.passi1_direct.setObjectName("passi1_direct")
        self.Motore1.addWidget(self.passi1_direct)
        self.ma1_direct = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma1_direct.sizePolicy().hasHeightForWidth())
        self.ma1_direct.setSizePolicy(sizePolicy)
        self.ma1_direct.setObjectName("ma1_direct")
        self.Motore1.addWidget(self.ma1_direct)
        self.ma1_value1_direct = QtWidgets.QLabel(self.layoutWidget)
        self.ma1_value1_direct.setObjectName("ma1_value1_direct")
        self.Motore1.addWidget(self.ma1_value1_direct)
        self.Vertical_layout_Direct.addLayout(self.Motore1)
        self.Motore2 = QtWidgets.QHBoxLayout()
        self.Motore2.setObjectName("Motore2")
        self.Encoder_direct = QtWidgets.QLabel(self.layoutWidget)
        self.Encoder_direct.setObjectName("Encoder_direct")
        self.Motore2.addWidget(self.Encoder_direct)
        self.riferimento1_2_direct = QtWidgets.QSpinBox(self.layoutWidget)
        self.riferimento1_2_direct.setObjectName("riferimento1_2_direct")
        self.Motore2.addWidget(self.riferimento1_2_direct)
        self.Step2_direct = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step2_direct.sizePolicy().hasHeightForWidth())
        self.Step2_direct.setSizePolicy(sizePolicy)
        self.Step2_direct.setObjectName("Step2_direct")
        self.Motore2.addWidget(self.Step2_direct)
        self.passi1_2_direct = QtWidgets.QLabel(self.layoutWidget)
        self.passi1_2_direct.setObjectName("passi1_2_direct")
        self.Motore2.addWidget(self.passi1_2_direct)
        self.ma2_direct = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma2_direct.sizePolicy().hasHeightForWidth())
        self.ma2_direct.setSizePolicy(sizePolicy)
        self.ma2_direct.setObjectName("ma2_direct")
        self.Motore2.addWidget(self.ma2_direct)
        self.ma2_value2_direct = QtWidgets.QLabel(self.layoutWidget)
        self.ma2_value2_direct.setObjectName("ma2_value2_direct")
        self.Motore2.addWidget(self.ma2_value2_direct)
        self.Vertical_layout_Direct.addLayout(self.Motore2)
        self.Motore3 = QtWidgets.QHBoxLayout()
        self.Motore3.setObjectName("Motore3")
        self.Encoder3_direct = QtWidgets.QLabel(self.layoutWidget)
        self.Encoder3_direct.setObjectName("Encoder3_direct")
        self.Motore3.addWidget(self.Encoder3_direct)
        self.riferimento1_3_direct = QtWidgets.QSpinBox(self.layoutWidget)
        self.riferimento1_3_direct.setObjectName("riferimento1_3_direct")
        self.Motore3.addWidget(self.riferimento1_3_direct)
        self.Step3_direct = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step3_direct.sizePolicy().hasHeightForWidth())
        self.Step3_direct.setSizePolicy(sizePolicy)
        self.Step3_direct.setObjectName("Step3_direct")
        self.Motore3.addWidget(self.Step3_direct)
        self.passi1_3_direct = QtWidgets.QLabel(self.layoutWidget)
        self.passi1_3_direct.setObjectName("passi1_3_direct")
        self.Motore3.addWidget(self.passi1_3_direct)
        self.ma3_direct = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma3_direct.sizePolicy().hasHeightForWidth())
        self.ma3_direct.setSizePolicy(sizePolicy)
        self.ma3_direct.setObjectName("ma3_direct")
        self.Motore3.addWidget(self.ma3_direct)
        self.ma3_value3_direct = QtWidgets.QLabel(self.layoutWidget)
        self.ma3_value3_direct.setObjectName("ma3_value3_direct")
        self.Motore3.addWidget(self.ma3_value3_direct)
        self.Vertical_layout_Direct.addLayout(self.Motore3)
        self.Motore4 = QtWidgets.QHBoxLayout()
        self.Motore4.setObjectName("Motore4")
        self.Ecoder4_direct = QtWidgets.QLabel(self.layoutWidget)
        self.Ecoder4_direct.setObjectName("Ecoder4_direct")
        self.Motore4.addWidget(self.Ecoder4_direct)
        self.riferimento1_4_direct = QtWidgets.QSpinBox(self.layoutWidget)
        self.riferimento1_4_direct.setObjectName("riferimento1_4_direct")
        self.Motore4.addWidget(self.riferimento1_4_direct)
        self.Step4_direct = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step4_direct.sizePolicy().hasHeightForWidth())
        self.Step4_direct.setSizePolicy(sizePolicy)
        self.Step4_direct.setObjectName("Step4_direct")
        self.Motore4.addWidget(self.Step4_direct)
        self.passi1_4_direct = QtWidgets.QLabel(self.layoutWidget)
        self.passi1_4_direct.setObjectName("passi1_4_direct")
        self.Motore4.addWidget(self.passi1_4_direct)
        self.ma4_direct = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma4_direct.sizePolicy().hasHeightForWidth())
        self.ma4_direct.setSizePolicy(sizePolicy)
        self.ma4_direct.setObjectName("ma4_direct")
        self.Motore4.addWidget(self.ma4_direct)
        self.ma4_value4_direct = QtWidgets.QLabel(self.layoutWidget)
        self.ma4_value4_direct.setObjectName("ma4_value4_direct")
        self.Motore4.addWidget(self.ma4_value4_direct)
        self.Vertical_layout_Direct.addLayout(self.Motore4)
        self.Motore5 = QtWidgets.QHBoxLayout()
        self.Motore5.setObjectName("Motore5")
        self.Encoder5_direct = QtWidgets.QLabel(self.layoutWidget)
        self.Encoder5_direct.setObjectName("Encoder5_direct")
        self.Motore5.addWidget(self.Encoder5_direct)
        self.riferimento1_5_direct = QtWidgets.QSpinBox(self.layoutWidget)
        self.riferimento1_5_direct.setObjectName("riferimento1_5_direct")
        self.Motore5.addWidget(self.riferimento1_5_direct)
        self.Step5_direct = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step5_direct.sizePolicy().hasHeightForWidth())
        self.Step5_direct.setSizePolicy(sizePolicy)
        self.Step5_direct.setObjectName("Step5_direct")
        self.Motore5.addWidget(self.Step5_direct)
        self.passi1_5_direct = QtWidgets.QLabel(self.layoutWidget)
        self.passi1_5_direct.setObjectName("passi1_5_direct")
        self.Motore5.addWidget(self.passi1_5_direct)
        self.ma5_direct = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma5_direct.sizePolicy().hasHeightForWidth())
        self.ma5_direct.setSizePolicy(sizePolicy)
        self.ma5_direct.setObjectName("ma5_direct")
        self.Motore5.addWidget(self.ma5_direct)
        self.ma5_value5_direct = QtWidgets.QLabel(self.layoutWidget)
        self.ma5_value5_direct.setObjectName("ma5_value5_direct")
        self.Motore5.addWidget(self.ma5_value5_direct)
        self.Vertical_layout_Direct.addLayout(self.Motore5)
        self.Motore6 = QtWidgets.QHBoxLayout()
        self.Motore6.setObjectName("Motore6")
        self.Encoder6_direct = QtWidgets.QLabel(self.layoutWidget)
        self.Encoder6_direct.setObjectName("Encoder6_direct")
        self.Motore6.addWidget(self.Encoder6_direct)
        self.riferimento1_6_direct = QtWidgets.QSpinBox(self.layoutWidget)
        self.riferimento1_6_direct.setObjectName("riferimento1_6_direct")
        self.Motore6.addWidget(self.riferimento1_6_direct)
        self.Step6_direct = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step6_direct.sizePolicy().hasHeightForWidth())
        self.Step6_direct.setSizePolicy(sizePolicy)
        self.Step6_direct.setObjectName("Step6_direct")
        self.Motore6.addWidget(self.Step6_direct)
        self.passi1_6_direct = QtWidgets.QLabel(self.layoutWidget)
        self.passi1_6_direct.setObjectName("passi1_6_direct")
        self.Motore6.addWidget(self.passi1_6_direct)
        self.ma6_direct = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma6_direct.sizePolicy().hasHeightForWidth())
        self.ma6_direct.setSizePolicy(sizePolicy)
        self.ma6_direct.setObjectName("ma6_direct")
        self.Motore6.addWidget(self.ma6_direct)
        self.ma6_value6_direct = QtWidgets.QLabel(self.layoutWidget)
        self.ma6_value6_direct.setObjectName("ma6_value6_direct")
        self.Motore6.addWidget(self.ma6_value6_direct)
        self.Vertical_layout_Direct.addLayout(self.Motore6)
        self.tabWidget.addTab(self.Direct, "")
        self.Direct_Angular = QtWidgets.QWidget()
        self.Direct_Angular.setObjectName("Direct_Angular")
        self.layoutWidget_6 = QtWidgets.QWidget(self.Direct_Angular)
        self.layoutWidget_6.setGeometry(QtCore.QRect(30, 60, 351, 241))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_Angular = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_Angular.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Angular.setObjectName("verticalLayout_Angular")
        self.Motore1_2 = QtWidgets.QHBoxLayout()
        self.Motore1_2.setObjectName("Motore1_2")
        self.Teta1_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Teta1_Angular.sizePolicy().hasHeightForWidth())
        self.Teta1_Angular.setSizePolicy(sizePolicy)
        self.Teta1_Angular.setObjectName("Teta1_Angular")
        self.Motore1_2.addWidget(self.Teta1_Angular)
        self.riferimento1_Angular = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.riferimento1_Angular.setObjectName("riferimento1_Angular")
        self.Motore1_2.addWidget(self.riferimento1_Angular)
        self.Step_Teta1_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step_Teta1_Angular.sizePolicy().hasHeightForWidth())
        self.Step_Teta1_Angular.setSizePolicy(sizePolicy)
        self.Step_Teta1_Angular.setObjectName("Step_Teta1_Angular")
        self.Motore1_2.addWidget(self.Step_Teta1_Angular)
        self.step1_Value_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        self.step1_Value_Angular.setObjectName("step1_Value_Angular")
        self.Motore1_2.addWidget(self.step1_Value_Angular)
        self.ma_Teta1_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma_Teta1_Angular.sizePolicy().hasHeightForWidth())
        self.ma_Teta1_Angular.setSizePolicy(sizePolicy)
        self.ma_Teta1_Angular.setObjectName("ma_Teta1_Angular")
        self.Motore1_2.addWidget(self.ma_Teta1_Angular)
        self.ma1_value_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        self.ma1_value_Angular.setObjectName("ma1_value_Angular")
        self.Motore1_2.addWidget(self.ma1_value_Angular)
        self.verticalLayout_Angular.addLayout(self.Motore1_2)
        self.Motore2_2 = QtWidgets.QHBoxLayout()
        self.Motore2_2.setObjectName("Motore2_2")
        self.Teta2_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Teta2_Angular.sizePolicy().hasHeightForWidth())
        self.Teta2_Angular.setSizePolicy(sizePolicy)
        self.Teta2_Angular.setObjectName("Teta2_Angular")
        self.Motore2_2.addWidget(self.Teta2_Angular)
        self.riferimento2_Angular = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.riferimento2_Angular.setObjectName("riferimento2_Angular")
        self.Motore2_2.addWidget(self.riferimento2_Angular)
        self.Step_Teta2_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step_Teta2_Angular.sizePolicy().hasHeightForWidth())
        self.Step_Teta2_Angular.setSizePolicy(sizePolicy)
        self.Step_Teta2_Angular.setObjectName("Step_Teta2_Angular")
        self.Motore2_2.addWidget(self.Step_Teta2_Angular)
        self.Step2_Value_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        self.Step2_Value_Angular.setObjectName("Step2_Value_Angular")
        self.Motore2_2.addWidget(self.Step2_Value_Angular)
        self.ma_Teta2_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma_Teta2_Angular.sizePolicy().hasHeightForWidth())
        self.ma_Teta2_Angular.setSizePolicy(sizePolicy)
        self.ma_Teta2_Angular.setObjectName("ma_Teta2_Angular")
        self.Motore2_2.addWidget(self.ma_Teta2_Angular)
        self.ma2_value_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        self.ma2_value_Angular.setObjectName("ma2_value_Angular")
        self.Motore2_2.addWidget(self.ma2_value_Angular)
        self.verticalLayout_Angular.addLayout(self.Motore2_2)
        self.Motore3_2 = QtWidgets.QHBoxLayout()
        self.Motore3_2.setObjectName("Motore3_2")
        self.Teta3_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Teta3_Angular.sizePolicy().hasHeightForWidth())
        self.Teta3_Angular.setSizePolicy(sizePolicy)
        self.Teta3_Angular.setObjectName("Teta3_Angular")
        self.Motore3_2.addWidget(self.Teta3_Angular)
        self.riferimento3_Angular = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.riferimento3_Angular.setObjectName("riferimento3_Angular")
        self.Motore3_2.addWidget(self.riferimento3_Angular)
        self.Step_Teta3_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step_Teta3_Angular.sizePolicy().hasHeightForWidth())
        self.Step_Teta3_Angular.setSizePolicy(sizePolicy)
        self.Step_Teta3_Angular.setObjectName("Step_Teta3_Angular")
        self.Motore3_2.addWidget(self.Step_Teta3_Angular)
        self.Step3_Value_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        self.Step3_Value_Angular.setObjectName("Step3_Value_Angular")
        self.Motore3_2.addWidget(self.Step3_Value_Angular)
        self.ma_teta3_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma_teta3_Angular.sizePolicy().hasHeightForWidth())
        self.ma_teta3_Angular.setSizePolicy(sizePolicy)
        self.ma_teta3_Angular.setObjectName("ma_teta3_Angular")
        self.Motore3_2.addWidget(self.ma_teta3_Angular)
        self.ma3_value_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        self.ma3_value_Angular.setObjectName("ma3_value_Angular")
        self.Motore3_2.addWidget(self.ma3_value_Angular)
        self.verticalLayout_Angular.addLayout(self.Motore3_2)
        self.Motore4_2 = QtWidgets.QHBoxLayout()
        self.Motore4_2.setObjectName("Motore4_2")
        self.Teta4_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Teta4_Angular.sizePolicy().hasHeightForWidth())
        self.Teta4_Angular.setSizePolicy(sizePolicy)
        self.Teta4_Angular.setObjectName("Teta4_Angular")
        self.Motore4_2.addWidget(self.Teta4_Angular)
        self.riferimento4_angular = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.riferimento4_angular.setObjectName("riferimento4_angular")
        self.Motore4_2.addWidget(self.riferimento4_angular)
        self.Step_Teta4_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step_Teta4_Angular.sizePolicy().hasHeightForWidth())
        self.Step_Teta4_Angular.setSizePolicy(sizePolicy)
        self.Step_Teta4_Angular.setObjectName("Step_Teta4_Angular")
        self.Motore4_2.addWidget(self.Step_Teta4_Angular)
        self.Step4_Value_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        self.Step4_Value_Angular.setObjectName("Step4_Value_Angular")
        self.Motore4_2.addWidget(self.Step4_Value_Angular)
        self.ma_teta4_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma_teta4_Angular.sizePolicy().hasHeightForWidth())
        self.ma_teta4_Angular.setSizePolicy(sizePolicy)
        self.ma_teta4_Angular.setObjectName("ma_teta4_Angular")
        self.Motore4_2.addWidget(self.ma_teta4_Angular)
        self.ma4_Value_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        self.ma4_Value_Angular.setObjectName("ma4_Value_Angular")
        self.Motore4_2.addWidget(self.ma4_Value_Angular)
        self.verticalLayout_Angular.addLayout(self.Motore4_2)
        self.Motore5_2 = QtWidgets.QHBoxLayout()
        self.Motore5_2.setObjectName("Motore5_2")
        self.Teta5_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Teta5_Angular.sizePolicy().hasHeightForWidth())
        self.Teta5_Angular.setSizePolicy(sizePolicy)
        self.Teta5_Angular.setObjectName("Teta5_Angular")
        self.Motore5_2.addWidget(self.Teta5_Angular)
        self.riferimento5_angular = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.riferimento5_angular.setObjectName("riferimento5_angular")
        self.Motore5_2.addWidget(self.riferimento5_angular)
        self.Step_Teta5_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step_Teta5_Angular.sizePolicy().hasHeightForWidth())
        self.Step_Teta5_Angular.setSizePolicy(sizePolicy)
        self.Step_Teta5_Angular.setObjectName("Step_Teta5_Angular")
        self.Motore5_2.addWidget(self.Step_Teta5_Angular)
        self.Step5_value_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        self.Step5_value_Angular.setObjectName("Step5_value_Angular")
        self.Motore5_2.addWidget(self.Step5_value_Angular)
        self.ma_teta5_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma_teta5_Angular.sizePolicy().hasHeightForWidth())
        self.ma_teta5_Angular.setSizePolicy(sizePolicy)
        self.ma_teta5_Angular.setObjectName("ma_teta5_Angular")
        self.Motore5_2.addWidget(self.ma_teta5_Angular)
        self.ma5_value_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        self.ma5_value_Angular.setObjectName("ma5_value_Angular")
        self.Motore5_2.addWidget(self.ma5_value_Angular)
        self.verticalLayout_Angular.addLayout(self.Motore5_2)
        self.Motore6_2 = QtWidgets.QHBoxLayout()
        self.Motore6_2.setObjectName("Motore6_2")
        self.Teta6_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Teta6_Angular.sizePolicy().hasHeightForWidth())
        self.Teta6_Angular.setSizePolicy(sizePolicy)
        self.Teta6_Angular.setObjectName("Teta6_Angular")
        self.Motore6_2.addWidget(self.Teta6_Angular)
        self.riferimento6_angular = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.riferimento6_angular.setObjectName("riferimento6_angular")
        self.Motore6_2.addWidget(self.riferimento6_angular)
        self.Step_Teta5_2_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step_Teta5_2_Angular.sizePolicy().hasHeightForWidth())
        self.Step_Teta5_2_Angular.setSizePolicy(sizePolicy)
        self.Step_Teta5_2_Angular.setObjectName("Step_Teta5_2_Angular")
        self.Motore6_2.addWidget(self.Step_Teta5_2_Angular)
        self.Step6_value_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        self.Step6_value_Angular.setObjectName("Step6_value_Angular")
        self.Motore6_2.addWidget(self.Step6_value_Angular)
        self.ma_teta_6_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma_teta_6_Angular.sizePolicy().hasHeightForWidth())
        self.ma_teta_6_Angular.setSizePolicy(sizePolicy)
        self.ma_teta_6_Angular.setObjectName("ma_teta_6_Angular")
        self.Motore6_2.addWidget(self.ma_teta_6_Angular)
        self.ma6_value_Angular = QtWidgets.QLabel(self.layoutWidget_6)
        self.ma6_value_Angular.setObjectName("ma6_value_Angular")
        self.Motore6_2.addWidget(self.ma6_value_Angular)
        self.verticalLayout_Angular.addLayout(self.Motore6_2)
        self.Angle = QtWidgets.QLabel(self.Direct_Angular)
        self.Angle.setGeometry(QtCore.QRect(160, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Angle.setFont(font)
        self.Angle.setObjectName("Angle")
        self.PulsanteInvioPAginaAdvance = QtWidgets.QPushButton(self.Direct_Angular)
        self.PulsanteInvioPAginaAdvance.setGeometry(QtCore.QRect(510, 130, 131, 41))
        self.PulsanteInvioPAginaAdvance.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0246305, y1:0.602273, x2:1, y2:0, stop:0 rgba(0, 139, 0, 255), stop:0.655172 rgba(255, 255, 255, 255));")
        self.PulsanteInvioPAginaAdvance.setObjectName("PulsanteInvioPAginaAdvance")
        self.tabWidget.addTab(self.Direct_Angular, "")
        self.Inverse = QtWidgets.QWidget()
        self.Inverse.setObjectName("Inverse")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Inverse)
        self.layoutWidget_2.setGeometry(QtCore.QRect(280, 60, 110, 39))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_Gomito_inverse = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_Gomito_inverse.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Gomito_inverse.setObjectName("verticalLayout_Gomito_inverse")
        self.Gomitoalto = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.Gomitoalto.setObjectName("Gomitoalto")
        self.verticalLayout_Gomito_inverse.addWidget(self.Gomitoalto)
        self.Gomitobasso = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.Gomitobasso.setObjectName("Gomitobasso")
        self.verticalLayout_Gomito_inverse.addWidget(self.Gomitobasso)
        self.layoutWidget_3 = QtWidgets.QWidget(self.Inverse)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 115, 231))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_X_Y_Z_Positizio_Inverse = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_X_Y_Z_Positizio_Inverse.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_X_Y_Z_Positizio_Inverse.setObjectName("verticalLayout_X_Y_Z_Positizio_Inverse")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Xdes = QtWidgets.QLabel(self.layoutWidget_3)
        self.Xdes.setObjectName("Xdes")
        self.horizontalLayout.addWidget(self.Xdes)
        self.Xdes_spin_Box = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.Xdes_spin_Box.setObjectName("Xdes_spin_Box")
        self.horizontalLayout.addWidget(self.Xdes_spin_Box)
        self.verticalLayout_X_Y_Z_Positizio_Inverse.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Ydes = QtWidgets.QLabel(self.layoutWidget_3)
        self.Ydes.setObjectName("Ydes")
        self.horizontalLayout_2.addWidget(self.Ydes)
        self.Ydes_spin_box = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.Ydes_spin_box.setObjectName("Ydes_spin_box")
        self.horizontalLayout_2.addWidget(self.Ydes_spin_box)
        self.verticalLayout_X_Y_Z_Positizio_Inverse.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Zdes = QtWidgets.QLabel(self.layoutWidget_3)
        self.Zdes.setObjectName("Zdes")
        self.horizontalLayout_3.addWidget(self.Zdes)
        self.Zdes_spin_Box = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.Zdes_spin_Box.setObjectName("Zdes_spin_Box")
        self.horizontalLayout_3.addWidget(self.Zdes_spin_Box)
        self.verticalLayout_X_Y_Z_Positizio_Inverse.addLayout(self.horizontalLayout_3)
        self.layoutWidget_4 = QtWidgets.QWidget(self.Inverse)
        self.layoutWidget_4.setGeometry(QtCore.QRect(530, 30, 51, 251))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.VerticalLayout_teta_Invere = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.VerticalLayout_teta_Invere.setContentsMargins(0, 0, 0, 0)
        self.VerticalLayout_teta_Invere.setObjectName("VerticalLayout_teta_Invere")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Teta1_inverse = QtWidgets.QLabel(self.layoutWidget_4)
        self.Teta1_inverse.setObjectName("Teta1_inverse")
        self.horizontalLayout_4.addWidget(self.Teta1_inverse)
        self.teta1_inverse_value = QtWidgets.QLabel(self.layoutWidget_4)
        self.teta1_inverse_value.setObjectName("teta1_inverse_value")
        self.horizontalLayout_4.addWidget(self.teta1_inverse_value)
        self.VerticalLayout_teta_Invere.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.teta2_inverse = QtWidgets.QLabel(self.layoutWidget_4)
        self.teta2_inverse.setObjectName("teta2_inverse")
        self.horizontalLayout_6.addWidget(self.teta2_inverse)
        self.teta2_inverse_value = QtWidgets.QLabel(self.layoutWidget_4)
        self.teta2_inverse_value.setObjectName("teta2_inverse_value")
        self.horizontalLayout_6.addWidget(self.teta2_inverse_value)
        self.VerticalLayout_teta_Invere.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.teta3_inverse = QtWidgets.QLabel(self.layoutWidget_4)
        self.teta3_inverse.setObjectName("teta3_inverse")
        self.horizontalLayout_5.addWidget(self.teta3_inverse)
        self.teta3_inverse_value = QtWidgets.QLabel(self.layoutWidget_4)
        self.teta3_inverse_value.setObjectName("teta3_inverse_value")
        self.horizontalLayout_5.addWidget(self.teta3_inverse_value)
        self.VerticalLayout_teta_Invere.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.teta4_inverse = QtWidgets.QLabel(self.layoutWidget_4)
        self.teta4_inverse.setObjectName("teta4_inverse")
        self.horizontalLayout_8.addWidget(self.teta4_inverse)
        self.teta4_inverse_value = QtWidgets.QLabel(self.layoutWidget_4)
        self.teta4_inverse_value.setObjectName("teta4_inverse_value")
        self.horizontalLayout_8.addWidget(self.teta4_inverse_value)
        self.VerticalLayout_teta_Invere.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.teta5_inverse = QtWidgets.QLabel(self.layoutWidget_4)
        self.teta5_inverse.setObjectName("teta5_inverse")
        self.horizontalLayout_7.addWidget(self.teta5_inverse)
        self.teta5_invers_value = QtWidgets.QLabel(self.layoutWidget_4)
        self.teta5_invers_value.setObjectName("teta5_invers_value")
        self.horizontalLayout_7.addWidget(self.teta5_invers_value)
        self.VerticalLayout_teta_Invere.addLayout(self.horizontalLayout_7)
        self.label = QtWidgets.QLabel(self.Inverse)
        self.label.setGeometry(QtCore.QRect(200, 310, 291, 151))
        self.label.setStyleSheet("url:(/image/Logo-Uni-Tor-Vergata.png_96x96.png)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.PulsanteInvioPAgina_Inverse = QtWidgets.QPushButton(self.Inverse)
        self.PulsanteInvioPAgina_Inverse.setGeometry(QtCore.QRect(650, 120, 131, 51))
        self.PulsanteInvioPAgina_Inverse.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0246305, y1:0.602273, x2:1, y2:0, stop:0 rgba(0, 139, 0, 255), stop:0.655172 rgba(255, 255, 255, 255));")
        self.PulsanteInvioPAgina_Inverse.setObjectName("PulsanteInvioPAgina_Inverse")
        self.tabWidget.addTab(self.Inverse, "")
        self.Setup = QtWidgets.QWidget()
        self.Setup.setObjectName("Setup")
        self.tabWidget.addTab(self.Setup, "")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(940, 50, 121, 141))
        self.image.setStyleSheet("url:(/newPrefix/Logo-Uni-Tor-Vergata.png_48x48.png)")
        self.image.setText("")
        self.image.setObjectName("image")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(1000, 40, 121, 151))
        self.label_39.setStyleSheet("image: url(:/image/Logo-Uni-Tor-Vergata.png_96x96.png);")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Immagine_tor_Vergata_Grande.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/Immagini/Logo-Uni-Tor-Vergata.png\"/></p></body></html>"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p>Direct</p><p><br/></p></body></html>"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>B</p><p><br/></p></body></html>"))
        self.Pulsante_invio_pagina_Basics.setText(_translate("MainWindow", "ENTER"))
        self.Passi_encoder_scritta.setText(_translate("MainWindow", "Encoder Steps "))
        self.Encoder1_direct.setText(_translate("MainWindow", "encoder n°1"))
        self.Step1_direct.setText(_translate("MainWindow", "Step:"))
        self.passi1_direct.setText(_translate("MainWindow", "0"))
        self.ma1_direct.setText(_translate("MainWindow", "mA:"))
        self.ma1_value1_direct.setText(_translate("MainWindow", "0"))
        self.Encoder_direct.setText(_translate("MainWindow", "encoder n°2"))
        self.Step2_direct.setText(_translate("MainWindow", "Step:"))
        self.passi1_2_direct.setText(_translate("MainWindow", "0"))
        self.ma2_direct.setText(_translate("MainWindow", "mA:"))
        self.ma2_value2_direct.setText(_translate("MainWindow", "0"))
        self.Encoder3_direct.setText(_translate("MainWindow", "encoder n°3"))
        self.Step3_direct.setText(_translate("MainWindow", "Step:"))
        self.passi1_3_direct.setText(_translate("MainWindow", "0"))
        self.ma3_direct.setText(_translate("MainWindow", "mA:"))
        self.ma3_value3_direct.setText(_translate("MainWindow", "0"))
        self.Ecoder4_direct.setText(_translate("MainWindow", "encoder n°4"))
        self.Step4_direct.setText(_translate("MainWindow", "Step:"))
        self.passi1_4_direct.setText(_translate("MainWindow", "0"))
        self.ma4_direct.setText(_translate("MainWindow", "mA:"))
        self.ma4_value4_direct.setText(_translate("MainWindow", "0"))
        self.Encoder5_direct.setText(_translate("MainWindow", "encoder n°5"))
        self.Step5_direct.setText(_translate("MainWindow", "Step:"))
        self.passi1_5_direct.setText(_translate("MainWindow", "0"))
        self.ma5_direct.setText(_translate("MainWindow", "mA:"))
        self.ma5_value5_direct.setText(_translate("MainWindow", "0"))
        self.Encoder6_direct.setText(_translate("MainWindow", "encoder n°6"))
        self.Step6_direct.setText(_translate("MainWindow", "Step:"))
        self.passi1_6_direct.setText(_translate("MainWindow", "0"))
        self.ma6_direct.setText(_translate("MainWindow", "mA:"))
        self.ma6_value6_direct.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Direct), _translate("MainWindow", "Direct  EncoderSteps"))
        self.Teta1_Angular.setText(_translate("MainWindow", "θ1:  "))
        self.Step_Teta1_Angular.setText(_translate("MainWindow", "Step:"))
        self.step1_Value_Angular.setText(_translate("MainWindow", "0"))
        self.ma_Teta1_Angular.setText(_translate("MainWindow", "mA:"))
        self.ma1_value_Angular.setText(_translate("MainWindow", "0"))
        self.Teta2_Angular.setText(_translate("MainWindow", "θ2:  "))
        self.Step_Teta2_Angular.setText(_translate("MainWindow", "Step:"))
        self.Step2_Value_Angular.setText(_translate("MainWindow", "0"))
        self.ma_Teta2_Angular.setText(_translate("MainWindow", "mA:"))
        self.ma2_value_Angular.setText(_translate("MainWindow", "0"))
        self.Teta3_Angular.setText(_translate("MainWindow", "θ3:  "))
        self.Step_Teta3_Angular.setText(_translate("MainWindow", "Step:"))
        self.Step3_Value_Angular.setText(_translate("MainWindow", "0"))
        self.ma_teta3_Angular.setText(_translate("MainWindow", "mA:"))
        self.ma3_value_Angular.setText(_translate("MainWindow", "0"))
        self.Teta4_Angular.setText(_translate("MainWindow", "θ4:  "))
        self.Step_Teta4_Angular.setText(_translate("MainWindow", "Step:"))
        self.Step4_Value_Angular.setText(_translate("MainWindow", "0"))
        self.ma_teta4_Angular.setText(_translate("MainWindow", "mA:"))
        self.ma4_Value_Angular.setText(_translate("MainWindow", "0"))
        self.Teta5_Angular.setText(_translate("MainWindow", "θ5:  "))
        self.Step_Teta5_Angular.setText(_translate("MainWindow", "Step:"))
        self.Step5_value_Angular.setText(_translate("MainWindow", "0"))
        self.ma_teta5_Angular.setText(_translate("MainWindow", "mA:"))
        self.ma5_value_Angular.setText(_translate("MainWindow", "0"))
        self.Teta6_Angular.setText(_translate("MainWindow", "θ6:  "))
        self.Step_Teta5_2_Angular.setText(_translate("MainWindow", "Step:"))
        self.Step6_value_Angular.setText(_translate("MainWindow", "0"))
        self.ma_teta_6_Angular.setText(_translate("MainWindow", "mA:"))
        self.ma6_value_Angular.setText(_translate("MainWindow", "0"))
        self.Angle.setText(_translate("MainWindow", "Angle"))
        self.PulsanteInvioPAginaAdvance.setText(_translate("MainWindow", "ENTER"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Direct_Angular), _translate("MainWindow", "Direct  AngularPosition"))
        self.Gomitoalto.setText(_translate("MainWindow", "Gomito alto"))
        self.Gomitobasso.setText(_translate("MainWindow", "Gomito basso"))
        self.Xdes.setText(_translate("MainWindow", "Xdes:"))
        self.Ydes.setText(_translate("MainWindow", "Ydes:"))
        self.Zdes.setText(_translate("MainWindow", "Zdes:"))
        self.Teta1_inverse.setText(_translate("MainWindow", "θ1:  "))
        self.teta1_inverse_value.setText(_translate("MainWindow", "0"))
        self.teta2_inverse.setText(_translate("MainWindow", "θ2:  "))
        self.teta2_inverse_value.setText(_translate("MainWindow", "0"))
        self.teta3_inverse.setText(_translate("MainWindow", "θ3:  "))
        self.teta3_inverse_value.setText(_translate("MainWindow", "0"))
        self.teta4_inverse.setText(_translate("MainWindow", "θ4:  "))
        self.teta4_inverse_value.setText(_translate("MainWindow", "0"))
        self.teta5_inverse.setText(_translate("MainWindow", "θ5:  "))
        self.teta5_invers_value.setText(_translate("MainWindow", "0"))
        self.PulsanteInvioPAgina_Inverse.setText(_translate("MainWindow", "ENTER"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Inverse), _translate("MainWindow", "Inverse  Kinematics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Setup), _translate("MainWindow", "Setup"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

