# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiClass.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UiClass(object):
    def setupUi(self, UiClass):
        UiClass.setObjectName("UiClass")
        UiClass.setEnabled(True)
        UiClass.resize(992, 439)
        UiClass.setStyleSheet("url:(/newPrefix/Logo-Uni-Tor-Vergata.png_48x48.png)")
        self.centralwidget = QtWidgets.QWidget(UiClass)
        self.centralwidget.setObjectName("centralwidget")
        self.o = QtWidgets.QTabWidget(self.centralwidget)
        self.o.setGeometry(QtCore.QRect(30, 10, 931, 381))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.o.setFont(font)
        self.o.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.o.setTabPosition(QtWidgets.QTabWidget.North)
        self.o.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.o.setUsesScrollButtons(False)
        self.o.setDocumentMode(False)
        self.o.setTabsClosable(False)
        self.o.setMovable(False)
        self.o.setTabBarAutoHide(False)
        self.o.setObjectName("o")
        self.Direct = QtWidgets.QWidget()
        self.Direct.setObjectName("Direct")
        self.Pulsante_invio_pagina_Basics = QtWidgets.QPushButton(self.Direct)
        self.Pulsante_invio_pagina_Basics.setGeometry(QtCore.QRect(730, 220, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Pulsante_invio_pagina_Basics.setFont(font)
        self.Pulsante_invio_pagina_Basics.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0246305, y1:0.602273, x2:1, y2:0, stop:0 rgba(0, 139, 0, 255), stop:0.655172 rgba(255, 255, 255, 255));")
        self.Pulsante_invio_pagina_Basics.setObjectName("Pulsante_invio_pagina_Basics")
        self.Passi_encoder_scritta = QtWidgets.QLabel(self.Direct)
        self.Passi_encoder_scritta.setGeometry(QtCore.QRect(10, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Passi_encoder_scritta.setFont(font)
        self.Passi_encoder_scritta.setObjectName("Passi_encoder_scritta")
        self.layoutWidget = QtWidgets.QWidget(self.Direct)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 171, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.VEn_Dir = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.VEn_Dir.setContentsMargins(0, 0, 0, 0)
        self.VEn_Dir.setSpacing(11)
        self.VEn_Dir.setObjectName("VEn_Dir")
        self.Motore1 = QtWidgets.QHBoxLayout()
        self.Motore1.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Motore1.setSpacing(0)
        self.Motore1.setObjectName("Motore1")
        self.Encoder1_direct = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Encoder1_direct.setFont(font)
        self.Encoder1_direct.setScaledContents(False)
        self.Encoder1_direct.setObjectName("Encoder1_direct")
        self.Motore1.addWidget(self.Encoder1_direct)
        self.riferimento1_direct = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.riferimento1_direct.setFont(font)
        self.riferimento1_direct.setObjectName("riferimento1_direct")
        self.Motore1.addWidget(self.riferimento1_direct)
        self.VEn_Dir.addLayout(self.Motore1)
        self.Motore2 = QtWidgets.QHBoxLayout()
        self.Motore2.setSpacing(0)
        self.Motore2.setObjectName("Motore2")
        self.Encoder_direct = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Encoder_direct.setFont(font)
        self.Encoder_direct.setObjectName("Encoder_direct")
        self.Motore2.addWidget(self.Encoder_direct)
        self.riferimento1_2_direct = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.riferimento1_2_direct.setFont(font)
        self.riferimento1_2_direct.setObjectName("riferimento1_2_direct")
        self.Motore2.addWidget(self.riferimento1_2_direct)
        self.VEn_Dir.addLayout(self.Motore2)
        self.Motore3 = QtWidgets.QHBoxLayout()
        self.Motore3.setSpacing(0)
        self.Motore3.setObjectName("Motore3")
        self.Encoder3_direct = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Encoder3_direct.setFont(font)
        self.Encoder3_direct.setObjectName("Encoder3_direct")
        self.Motore3.addWidget(self.Encoder3_direct)
        self.riferimento1_3_direct = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.riferimento1_3_direct.setFont(font)
        self.riferimento1_3_direct.setObjectName("riferimento1_3_direct")
        self.Motore3.addWidget(self.riferimento1_3_direct)
        self.VEn_Dir.addLayout(self.Motore3)
        self.Motore4 = QtWidgets.QHBoxLayout()
        self.Motore4.setSpacing(0)
        self.Motore4.setObjectName("Motore4")
        self.Ecoder4_direct = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Ecoder4_direct.setFont(font)
        self.Ecoder4_direct.setObjectName("Ecoder4_direct")
        self.Motore4.addWidget(self.Ecoder4_direct)
        self.riferimento1_4_direct = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.riferimento1_4_direct.setFont(font)
        self.riferimento1_4_direct.setObjectName("riferimento1_4_direct")
        self.Motore4.addWidget(self.riferimento1_4_direct)
        self.VEn_Dir.addLayout(self.Motore4)
        self.Motore5 = QtWidgets.QHBoxLayout()
        self.Motore5.setSpacing(0)
        self.Motore5.setObjectName("Motore5")
        self.Encoder5_direct = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Encoder5_direct.setFont(font)
        self.Encoder5_direct.setObjectName("Encoder5_direct")
        self.Motore5.addWidget(self.Encoder5_direct)
        self.riferimento1_5_direct = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.riferimento1_5_direct.setFont(font)
        self.riferimento1_5_direct.setObjectName("riferimento1_5_direct")
        self.Motore5.addWidget(self.riferimento1_5_direct)
        self.VEn_Dir.addLayout(self.Motore5)
        self.Motore6 = QtWidgets.QHBoxLayout()
        self.Motore6.setSpacing(0)
        self.Motore6.setObjectName("Motore6")
        self.Encoder6_direct = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Encoder6_direct.setFont(font)
        self.Encoder6_direct.setObjectName("Encoder6_direct")
        self.Motore6.addWidget(self.Encoder6_direct)
        self.riferimento1_6_direct = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.riferimento1_6_direct.setFont(font)
        self.riferimento1_6_direct.setObjectName("riferimento1_6_direct")
        self.Motore6.addWidget(self.riferimento1_6_direct)
        self.VEn_Dir.addLayout(self.Motore6)
        self.layoutWidget1 = QtWidgets.QWidget(self.Direct)
        self.layoutWidget1.setGeometry(QtCore.QRect(330, 40, 141, 271))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.VEncDir = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.VEncDir.setContentsMargins(0, 0, 0, 0)
        self.VEncDir.setSpacing(10)
        self.VEncDir.setObjectName("VEncDir")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.encrease1 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease1.setFont(font)
        self.encrease1.setObjectName("encrease1")
        self.horizontalLayout_9.addWidget(self.encrease1)
        self.encrease_value1 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease_value1.setFont(font)
        self.encrease_value1.setObjectName("encrease_value1")
        self.horizontalLayout_9.addWidget(self.encrease_value1)
        self.VEncDir.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.encrease2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease2.setFont(font)
        self.encrease2.setObjectName("encrease2")
        self.horizontalLayout_14.addWidget(self.encrease2)
        self.encrease_value2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease_value2.setFont(font)
        self.encrease_value2.setObjectName("encrease_value2")
        self.horizontalLayout_14.addWidget(self.encrease_value2)
        self.VEncDir.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.encrease3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease3.setFont(font)
        self.encrease3.setIndent(-1)
        self.encrease3.setObjectName("encrease3")
        self.horizontalLayout_15.addWidget(self.encrease3)
        self.encrease_value3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease_value3.setFont(font)
        self.encrease_value3.setObjectName("encrease_value3")
        self.horizontalLayout_15.addWidget(self.encrease_value3)
        self.VEncDir.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.encrease4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease4.setFont(font)
        self.encrease4.setScaledContents(False)
        self.encrease4.setObjectName("encrease4")
        self.horizontalLayout_16.addWidget(self.encrease4)
        self.encrease_value4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease_value4.setFont(font)
        self.encrease_value4.setObjectName("encrease_value4")
        self.horizontalLayout_16.addWidget(self.encrease_value4)
        self.VEncDir.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.encrease5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease5.setFont(font)
        self.encrease5.setObjectName("encrease5")
        self.horizontalLayout_17.addWidget(self.encrease5)
        self.encrease_value5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease_value5.setFont(font)
        self.encrease_value5.setObjectName("encrease_value5")
        self.horizontalLayout_17.addWidget(self.encrease_value5)
        self.VEncDir.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.encrease6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease6.setFont(font)
        self.encrease6.setObjectName("encrease6")
        self.horizontalLayout_18.addWidget(self.encrease6)
        self.encrease_value6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease_value6.setFont(font)
        self.encrease_value6.setObjectName("encrease_value6")
        self.horizontalLayout_18.addWidget(self.encrease_value6)
        self.VEncDir.addLayout(self.horizontalLayout_18)
        self.layoutWidget2 = QtWidgets.QWidget(self.Direct)
        self.layoutWidget2.setGeometry(QtCore.QRect(210, 40, 111, 271))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.layoutWidget2.setFont(font)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.VStepDir = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.VStepDir.setContentsMargins(0, 0, 0, 0)
        self.VStepDir.setSpacing(12)
        self.VStepDir.setObjectName("VStepDir")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.Step1_direct = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step1_direct.sizePolicy().hasHeightForWidth())
        self.Step1_direct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Step1_direct.setFont(font)
        self.Step1_direct.setObjectName("Step1_direct")
        self.horizontalLayout_25.addWidget(self.Step1_direct)
        self.passi1_direct = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passi1_direct.setFont(font)
        self.passi1_direct.setObjectName("passi1_direct")
        self.horizontalLayout_25.addWidget(self.passi1_direct)
        self.VStepDir.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.Step2_direct = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step2_direct.sizePolicy().hasHeightForWidth())
        self.Step2_direct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Step2_direct.setFont(font)
        self.Step2_direct.setObjectName("Step2_direct")
        self.horizontalLayout_26.addWidget(self.Step2_direct)
        self.passi1_2_direct = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passi1_2_direct.setFont(font)
        self.passi1_2_direct.setObjectName("passi1_2_direct")
        self.horizontalLayout_26.addWidget(self.passi1_2_direct)
        self.VStepDir.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.Step3_direct = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step3_direct.sizePolicy().hasHeightForWidth())
        self.Step3_direct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Step3_direct.setFont(font)
        self.Step3_direct.setObjectName("Step3_direct")
        self.horizontalLayout_27.addWidget(self.Step3_direct)
        self.passi1_3_direct = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passi1_3_direct.setFont(font)
        self.passi1_3_direct.setObjectName("passi1_3_direct")
        self.horizontalLayout_27.addWidget(self.passi1_3_direct)
        self.VStepDir.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.Step4_direct = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step4_direct.sizePolicy().hasHeightForWidth())
        self.Step4_direct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Step4_direct.setFont(font)
        self.Step4_direct.setObjectName("Step4_direct")
        self.horizontalLayout_28.addWidget(self.Step4_direct)
        self.passi1_4_direct = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passi1_4_direct.setFont(font)
        self.passi1_4_direct.setObjectName("passi1_4_direct")
        self.horizontalLayout_28.addWidget(self.passi1_4_direct)
        self.VStepDir.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.Step5_direct = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step5_direct.sizePolicy().hasHeightForWidth())
        self.Step5_direct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Step5_direct.setFont(font)
        self.Step5_direct.setObjectName("Step5_direct")
        self.horizontalLayout_29.addWidget(self.Step5_direct)
        self.passi1_5_direct = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passi1_5_direct.setFont(font)
        self.passi1_5_direct.setObjectName("passi1_5_direct")
        self.horizontalLayout_29.addWidget(self.passi1_5_direct)
        self.VStepDir.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.Step6_direct = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step6_direct.sizePolicy().hasHeightForWidth())
        self.Step6_direct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Step6_direct.setFont(font)
        self.Step6_direct.setObjectName("Step6_direct")
        self.horizontalLayout_30.addWidget(self.Step6_direct)
        self.passi1_6_direct = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passi1_6_direct.setFont(font)
        self.passi1_6_direct.setObjectName("passi1_6_direct")
        self.horizontalLayout_30.addWidget(self.passi1_6_direct)
        self.VStepDir.addLayout(self.horizontalLayout_30)
        self.layoutWidget_5 = QtWidgets.QWidget(self.Direct)
        self.layoutWidget_5.setGeometry(QtCore.QRect(490, 40, 131, 271))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.layoutWidget_5.setFont(font)
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.VmADir_2 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.VmADir_2.setContentsMargins(0, 0, 0, 0)
        self.VmADir_2.setSpacing(10)
        self.VmADir_2.setObjectName("VmADir_2")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.ma1 = QtWidgets.QLabel(self.layoutWidget_5)
        self.ma1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma1.sizePolicy().hasHeightForWidth())
        self.ma1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma1.setFont(font)
        self.ma1.setObjectName("ma1")
        self.horizontalLayout_37.addWidget(self.ma1)
        self.ma1_value = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma1_value.setFont(font)
        self.ma1_value.setObjectName("ma1_value")
        self.horizontalLayout_37.addWidget(self.ma1_value)
        self.VmADir_2.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.ma2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.ma2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma2.sizePolicy().hasHeightForWidth())
        self.ma2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma2.setFont(font)
        self.ma2.setObjectName("ma2")
        self.horizontalLayout_38.addWidget(self.ma2)
        self.ma2_value = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma2_value.setFont(font)
        self.ma2_value.setObjectName("ma2_value")
        self.horizontalLayout_38.addWidget(self.ma2_value)
        self.VmADir_2.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.ma3 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma3.sizePolicy().hasHeightForWidth())
        self.ma3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma3.setFont(font)
        self.ma3.setObjectName("ma3")
        self.horizontalLayout_39.addWidget(self.ma3)
        self.ma3_value = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma3_value.setFont(font)
        self.ma3_value.setObjectName("ma3_value")
        self.horizontalLayout_39.addWidget(self.ma3_value)
        self.VmADir_2.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.ma4 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma4.sizePolicy().hasHeightForWidth())
        self.ma4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma4.setFont(font)
        self.ma4.setObjectName("ma4")
        self.horizontalLayout_40.addWidget(self.ma4)
        self.ma4_value = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma4_value.setFont(font)
        self.ma4_value.setObjectName("ma4_value")
        self.horizontalLayout_40.addWidget(self.ma4_value)
        self.VmADir_2.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.ma5 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma5.sizePolicy().hasHeightForWidth())
        self.ma5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma5.setFont(font)
        self.ma5.setObjectName("ma5")
        self.horizontalLayout_41.addWidget(self.ma5)
        self.ma5_value = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma5_value.setFont(font)
        self.ma5_value.setObjectName("ma5_value")
        self.horizontalLayout_41.addWidget(self.ma5_value)
        self.VmADir_2.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.ma6 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma6.sizePolicy().hasHeightForWidth())
        self.ma6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma6.setFont(font)
        self.ma6.setObjectName("ma6")
        self.horizontalLayout_42.addWidget(self.ma6)
        self.ma6_value = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma6_value.setFont(font)
        self.ma6_value.setObjectName("ma6_value")
        self.horizontalLayout_42.addWidget(self.ma6_value)
        self.VmADir_2.addLayout(self.horizontalLayout_42)
        self.Open1 = QtWidgets.QPushButton(self.Direct)
        self.Open1.setGeometry(QtCore.QRect(700, 290, 81, 32))
        self.Open1.setStyleSheet("background-color: rgb(255, 255, 247);")
        self.Open1.setObjectName("Open1")
        self.Close1 = QtWidgets.QPushButton(self.Direct)
        self.Close1.setGeometry(QtCore.QRect(810, 290, 81, 32))
        self.Close1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Close1.setObjectName("Close1")
        self.o.addTab(self.Direct, "")
        self.Direct_Angular = QtWidgets.QWidget()
        self.Direct_Angular.setObjectName("Direct_Angular")
        self.Angle = QtWidgets.QLabel(self.Direct_Angular)
        self.Angle.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Angle.setFont(font)
        self.Angle.setObjectName("Angle")
        self.PulsanteInvioPAginaAdvance = QtWidgets.QPushButton(self.Direct_Angular)
        self.PulsanteInvioPAginaAdvance.setGeometry(QtCore.QRect(730, 220, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PulsanteInvioPAginaAdvance.setFont(font)
        self.PulsanteInvioPAginaAdvance.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0246305, y1:0.602273, x2:1, y2:0, stop:0 rgba(0, 139, 0, 255), stop:0.655172 rgba(255, 255, 255, 255));")
        self.PulsanteInvioPAginaAdvance.setObjectName("PulsanteInvioPAginaAdvance")
        self.layoutWidget3 = QtWidgets.QWidget(self.Direct_Angular)
        self.layoutWidget3.setGeometry(QtCore.QRect(490, 40, 111, 271))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.layoutWidget3.setFont(font)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.VmADir = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.VmADir.setContentsMargins(0, 0, 0, 0)
        self.VmADir.setSpacing(10)
        self.VmADir.setObjectName("VmADir")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.ma1_direct = QtWidgets.QLabel(self.layoutWidget3)
        self.ma1_direct.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma1_direct.sizePolicy().hasHeightForWidth())
        self.ma1_direct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma1_direct.setFont(font)
        self.ma1_direct.setObjectName("ma1_direct")
        self.horizontalLayout_19.addWidget(self.ma1_direct)
        self.ma1_value1_direct = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma1_value1_direct.setFont(font)
        self.ma1_value1_direct.setObjectName("ma1_value1_direct")
        self.horizontalLayout_19.addWidget(self.ma1_value1_direct)
        self.VmADir.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.ma2_direct = QtWidgets.QLabel(self.layoutWidget3)
        self.ma2_direct.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma2_direct.sizePolicy().hasHeightForWidth())
        self.ma2_direct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma2_direct.setFont(font)
        self.ma2_direct.setObjectName("ma2_direct")
        self.horizontalLayout_20.addWidget(self.ma2_direct)
        self.ma2_value2_direct = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma2_value2_direct.setFont(font)
        self.ma2_value2_direct.setObjectName("ma2_value2_direct")
        self.horizontalLayout_20.addWidget(self.ma2_value2_direct)
        self.VmADir.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.ma3_direct = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma3_direct.sizePolicy().hasHeightForWidth())
        self.ma3_direct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma3_direct.setFont(font)
        self.ma3_direct.setObjectName("ma3_direct")
        self.horizontalLayout_21.addWidget(self.ma3_direct)
        self.ma3_value3_direct = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma3_value3_direct.setFont(font)
        self.ma3_value3_direct.setObjectName("ma3_value3_direct")
        self.horizontalLayout_21.addWidget(self.ma3_value3_direct)
        self.VmADir.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.ma4_direct = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma4_direct.sizePolicy().hasHeightForWidth())
        self.ma4_direct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma4_direct.setFont(font)
        self.ma4_direct.setObjectName("ma4_direct")
        self.horizontalLayout_22.addWidget(self.ma4_direct)
        self.ma4_value4_direct = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma4_value4_direct.setFont(font)
        self.ma4_value4_direct.setObjectName("ma4_value4_direct")
        self.horizontalLayout_22.addWidget(self.ma4_value4_direct)
        self.VmADir.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.ma5_direct = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma5_direct.sizePolicy().hasHeightForWidth())
        self.ma5_direct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma5_direct.setFont(font)
        self.ma5_direct.setObjectName("ma5_direct")
        self.horizontalLayout_23.addWidget(self.ma5_direct)
        self.ma5_value5_direct = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma5_value5_direct.setFont(font)
        self.ma5_value5_direct.setObjectName("ma5_value5_direct")
        self.horizontalLayout_23.addWidget(self.ma5_value5_direct)
        self.VmADir.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.ma6_direct = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma6_direct.sizePolicy().hasHeightForWidth())
        self.ma6_direct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma6_direct.setFont(font)
        self.ma6_direct.setObjectName("ma6_direct")
        self.horizontalLayout_24.addWidget(self.ma6_direct)
        self.ma6_value6_direct = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ma6_value6_direct.setFont(font)
        self.ma6_value6_direct.setObjectName("ma6_value6_direct")
        self.horizontalLayout_24.addWidget(self.ma6_value6_direct)
        self.VmADir.addLayout(self.horizontalLayout_24)
        self.layoutWidget_7 = QtWidgets.QWidget(self.Direct_Angular)
        self.layoutWidget_7.setGeometry(QtCore.QRect(210, 40, 111, 271))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.layoutWidget_7.setFont(font)
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.VStepDir_2 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.VStepDir_2.setContentsMargins(0, 0, 0, 0)
        self.VStepDir_2.setSpacing(12)
        self.VStepDir_2.setObjectName("VStepDir_2")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.teta1_dir = QtWidgets.QLabel(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teta1_dir.sizePolicy().hasHeightForWidth())
        self.teta1_dir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teta1_dir.setFont(font)
        self.teta1_dir.setObjectName("teta1_dir")
        self.horizontalLayout_31.addWidget(self.teta1_dir)
        self.tetaDir_1value = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tetaDir_1value.setFont(font)
        self.tetaDir_1value.setObjectName("tetaDir_1value")
        self.horizontalLayout_31.addWidget(self.tetaDir_1value)
        self.VStepDir_2.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.teta2_dir = QtWidgets.QLabel(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teta2_dir.sizePolicy().hasHeightForWidth())
        self.teta2_dir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teta2_dir.setFont(font)
        self.teta2_dir.setObjectName("teta2_dir")
        self.horizontalLayout_32.addWidget(self.teta2_dir)
        self.tetaDir_2value = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tetaDir_2value.setFont(font)
        self.tetaDir_2value.setObjectName("tetaDir_2value")
        self.horizontalLayout_32.addWidget(self.tetaDir_2value)
        self.VStepDir_2.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.teta3_dit = QtWidgets.QLabel(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teta3_dit.sizePolicy().hasHeightForWidth())
        self.teta3_dit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teta3_dit.setFont(font)
        self.teta3_dit.setObjectName("teta3_dit")
        self.horizontalLayout_33.addWidget(self.teta3_dit)
        self.tetaDir_3value = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tetaDir_3value.setFont(font)
        self.tetaDir_3value.setObjectName("tetaDir_3value")
        self.horizontalLayout_33.addWidget(self.tetaDir_3value)
        self.VStepDir_2.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.teta4_dit = QtWidgets.QLabel(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teta4_dit.sizePolicy().hasHeightForWidth())
        self.teta4_dit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teta4_dit.setFont(font)
        self.teta4_dit.setObjectName("teta4_dit")
        self.horizontalLayout_34.addWidget(self.teta4_dit)
        self.tetaDir_4value = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tetaDir_4value.setFont(font)
        self.tetaDir_4value.setObjectName("tetaDir_4value")
        self.horizontalLayout_34.addWidget(self.tetaDir_4value)
        self.VStepDir_2.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.teta5_dir = QtWidgets.QLabel(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teta5_dir.sizePolicy().hasHeightForWidth())
        self.teta5_dir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teta5_dir.setFont(font)
        self.teta5_dir.setObjectName("teta5_dir")
        self.horizontalLayout_35.addWidget(self.teta5_dir)
        self.tetaDir_5value = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tetaDir_5value.setFont(font)
        self.tetaDir_5value.setObjectName("tetaDir_5value")
        self.horizontalLayout_35.addWidget(self.tetaDir_5value)
        self.VStepDir_2.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.teta6_dir = QtWidgets.QLabel(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teta6_dir.sizePolicy().hasHeightForWidth())
        self.teta6_dir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teta6_dir.setFont(font)
        self.teta6_dir.setObjectName("teta6_dir")
        self.horizontalLayout_36.addWidget(self.teta6_dir)
        self.tetaDir_6value = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tetaDir_6value.setFont(font)
        self.tetaDir_6value.setObjectName("tetaDir_6value")
        self.horizontalLayout_36.addWidget(self.tetaDir_6value)
        self.VStepDir_2.addLayout(self.horizontalLayout_36)
        self.layoutWidget_9 = QtWidgets.QWidget(self.Direct_Angular)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 40, 171, 281))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.VEn_Dir_3 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.VEn_Dir_3.setContentsMargins(0, 0, 0, 0)
        self.VEn_Dir_3.setSpacing(11)
        self.VEn_Dir_3.setObjectName("VEn_Dir_3")
        self.Motore1_3 = QtWidgets.QHBoxLayout()
        self.Motore1_3.setObjectName("Motore1_3")
        self.Angle1_dir = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Angle1_dir.setFont(font)
        self.Angle1_dir.setObjectName("Angle1_dir")
        self.Motore1_3.addWidget(self.Angle1_dir)
        self.AngleDir_1 = QtWidgets.QSpinBox(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AngleDir_1.setFont(font)
        self.AngleDir_1.setObjectName("AngleDir_1")
        self.Motore1_3.addWidget(self.AngleDir_1)
        self.VEn_Dir_3.addLayout(self.Motore1_3)
        self.Motore2_3 = QtWidgets.QHBoxLayout()
        self.Motore2_3.setObjectName("Motore2_3")
        self.Angle2_dir = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Angle2_dir.setFont(font)
        self.Angle2_dir.setObjectName("Angle2_dir")
        self.Motore2_3.addWidget(self.Angle2_dir)
        self.AngleDir_2 = QtWidgets.QSpinBox(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AngleDir_2.setFont(font)
        self.AngleDir_2.setObjectName("AngleDir_2")
        self.Motore2_3.addWidget(self.AngleDir_2)
        self.VEn_Dir_3.addLayout(self.Motore2_3)
        self.Motore3_3 = QtWidgets.QHBoxLayout()
        self.Motore3_3.setObjectName("Motore3_3")
        self.Angle3_dir = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Angle3_dir.setFont(font)
        self.Angle3_dir.setObjectName("Angle3_dir")
        self.Motore3_3.addWidget(self.Angle3_dir)
        self.AngleDir_3 = QtWidgets.QSpinBox(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AngleDir_3.setFont(font)
        self.AngleDir_3.setObjectName("AngleDir_3")
        self.Motore3_3.addWidget(self.AngleDir_3)
        self.VEn_Dir_3.addLayout(self.Motore3_3)
        self.Motore4_3 = QtWidgets.QHBoxLayout()
        self.Motore4_3.setObjectName("Motore4_3")
        self.Angle4_dir = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Angle4_dir.setFont(font)
        self.Angle4_dir.setObjectName("Angle4_dir")
        self.Motore4_3.addWidget(self.Angle4_dir)
        self.AngleDir_4 = QtWidgets.QSpinBox(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AngleDir_4.setFont(font)
        self.AngleDir_4.setObjectName("AngleDir_4")
        self.Motore4_3.addWidget(self.AngleDir_4)
        self.VEn_Dir_3.addLayout(self.Motore4_3)
        self.Motore5_3 = QtWidgets.QHBoxLayout()
        self.Motore5_3.setObjectName("Motore5_3")
        self.Angle5_dir = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Angle5_dir.setFont(font)
        self.Angle5_dir.setObjectName("Angle5_dir")
        self.Motore5_3.addWidget(self.Angle5_dir)
        self.AngleDir_5 = QtWidgets.QSpinBox(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AngleDir_5.setFont(font)
        self.AngleDir_5.setObjectName("AngleDir_5")
        self.Motore5_3.addWidget(self.AngleDir_5)
        self.VEn_Dir_3.addLayout(self.Motore5_3)
        self.Motore6_3 = QtWidgets.QHBoxLayout()
        self.Motore6_3.setObjectName("Motore6_3")
        self.Angle6_dir = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Angle6_dir.setFont(font)
        self.Angle6_dir.setObjectName("Angle6_dir")
        self.Motore6_3.addWidget(self.Angle6_dir)
        self.AngleDir_6 = QtWidgets.QSpinBox(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AngleDir_6.setFont(font)
        self.AngleDir_6.setObjectName("AngleDir_6")
        self.Motore6_3.addWidget(self.AngleDir_6)
        self.VEn_Dir_3.addLayout(self.Motore6_3)
        self.layoutWidget_8 = QtWidgets.QWidget(self.Direct_Angular)
        self.layoutWidget_8.setGeometry(QtCore.QRect(330, 40, 141, 271))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layoutWidget_8.setFont(font)
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.VEncDir_2 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.VEncDir_2.setContentsMargins(0, 0, 0, 0)
        self.VEncDir_2.setSpacing(10)
        self.VEncDir_2.setObjectName("VEncDir_2")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.encrease1_2 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease1_2.setFont(font)
        self.encrease1_2.setObjectName("encrease1_2")
        self.horizontalLayout_49.addWidget(self.encrease1_2)
        self.encrease_value1_2 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease_value1_2.setFont(font)
        self.encrease_value1_2.setObjectName("encrease_value1_2")
        self.horizontalLayout_49.addWidget(self.encrease_value1_2)
        self.VEncDir_2.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.encrease2_2 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease2_2.setFont(font)
        self.encrease2_2.setObjectName("encrease2_2")
        self.horizontalLayout_50.addWidget(self.encrease2_2)
        self.encrease_value2_2 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease_value2_2.setFont(font)
        self.encrease_value2_2.setObjectName("encrease_value2_2")
        self.horizontalLayout_50.addWidget(self.encrease_value2_2)
        self.VEncDir_2.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.encrease3_2 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease3_2.setFont(font)
        self.encrease3_2.setIndent(-1)
        self.encrease3_2.setObjectName("encrease3_2")
        self.horizontalLayout_51.addWidget(self.encrease3_2)
        self.encrease_value3_2 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease_value3_2.setFont(font)
        self.encrease_value3_2.setObjectName("encrease_value3_2")
        self.horizontalLayout_51.addWidget(self.encrease_value3_2)
        self.VEncDir_2.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.encrease4_2 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease4_2.setFont(font)
        self.encrease4_2.setScaledContents(False)
        self.encrease4_2.setObjectName("encrease4_2")
        self.horizontalLayout_52.addWidget(self.encrease4_2)
        self.encrease_value4_2 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease_value4_2.setFont(font)
        self.encrease_value4_2.setObjectName("encrease_value4_2")
        self.horizontalLayout_52.addWidget(self.encrease_value4_2)
        self.VEncDir_2.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.encrease5_2 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease5_2.setFont(font)
        self.encrease5_2.setObjectName("encrease5_2")
        self.horizontalLayout_53.addWidget(self.encrease5_2)
        self.encrease_value5_2 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease_value5_2.setFont(font)
        self.encrease_value5_2.setObjectName("encrease_value5_2")
        self.horizontalLayout_53.addWidget(self.encrease_value5_2)
        self.VEncDir_2.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.encrease6_2 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease6_2.setFont(font)
        self.encrease6_2.setObjectName("encrease6_2")
        self.horizontalLayout_54.addWidget(self.encrease6_2)
        self.encrease_value6_2 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encrease_value6_2.setFont(font)
        self.encrease_value6_2.setObjectName("encrease_value6_2")
        self.horizontalLayout_54.addWidget(self.encrease_value6_2)
        self.VEncDir_2.addLayout(self.horizontalLayout_54)
        self.image_2 = QtWidgets.QLabel(self.Direct_Angular)
        self.image_2.setGeometry(QtCore.QRect(1789, 59, 141, 141))
        self.image_2.setStyleSheet("image: url(:/image/Logo-Uni-Tor-Vergata.png_256x256.png);")
        self.image_2.setText("")
        self.image_2.setObjectName("image_2")
        self.layoutWidget4 = QtWidgets.QWidget(self.Direct_Angular)
        self.layoutWidget4.setGeometry(QtCore.QRect(610, 50, 71, 136))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.alpha_6 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alpha_6.setFont(font)
        self.alpha_6.setObjectName("alpha_6")
        self.horizontalLayout_10.addWidget(self.alpha_6)
        self.alphaValue = QtWidgets.QSpinBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alphaValue.setFont(font)
        self.alphaValue.setObjectName("alphaValue")
        self.horizontalLayout_10.addWidget(self.alphaValue)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.beta_4 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.beta_4.setFont(font)
        self.beta_4.setObjectName("beta_4")
        self.horizontalLayout_11.addWidget(self.beta_4)
        self.betaValue = QtWidgets.QSpinBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.betaValue.setFont(font)
        self.betaValue.setObjectName("betaValue")
        self.horizontalLayout_11.addWidget(self.betaValue)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gamma_3 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gamma_3.setFont(font)
        self.gamma_3.setObjectName("gamma_3")
        self.horizontalLayout_12.addWidget(self.gamma_3)
        self.gammaValue = QtWidgets.QSpinBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gammaValue.setFont(font)
        self.gammaValue.setObjectName("gammaValue")
        self.horizontalLayout_12.addWidget(self.gammaValue)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.delta_3 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delta_3.setFont(font)
        self.delta_3.setObjectName("delta_3")
        self.horizontalLayout_13.addWidget(self.delta_3)
        self.deltaValue = QtWidgets.QSpinBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deltaValue.setFont(font)
        self.deltaValue.setObjectName("deltaValue")
        self.horizontalLayout_13.addWidget(self.deltaValue)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.open2 = QtWidgets.QPushButton(self.Direct_Angular)
        self.open2.setGeometry(QtCore.QRect(700, 290, 81, 32))
        self.open2.setStyleSheet("background-color: rgb(255, 255, 247);")
        self.open2.setObjectName("open2")
        self.close2 = QtWidgets.QPushButton(self.Direct_Angular)
        self.close2.setGeometry(QtCore.QRect(810, 290, 81, 32))
        self.close2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.close2.setObjectName("close2")
        self.o.addTab(self.Direct_Angular, "")
        self.Inverse = QtWidgets.QWidget()
        self.Inverse.setObjectName("Inverse")
        self.layoutWidget_4 = QtWidgets.QWidget(self.Inverse)
        self.layoutWidget_4.setGeometry(QtCore.QRect(560, 40, 121, 251))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.layoutWidget_4.setFont(font)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.VerticalLayout_teta_Invere = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.VerticalLayout_teta_Invere.setContentsMargins(0, 0, 0, 0)
        self.VerticalLayout_teta_Invere.setObjectName("VerticalLayout_teta_Invere")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Teta1_inverse = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Teta1_inverse.setFont(font)
        self.Teta1_inverse.setStyleSheet("")
        self.Teta1_inverse.setObjectName("Teta1_inverse")
        self.horizontalLayout_4.addWidget(self.Teta1_inverse)
        self.teta1_inverse_value = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.teta1_inverse_value.setFont(font)
        self.teta1_inverse_value.setStyleSheet("")
        self.teta1_inverse_value.setObjectName("teta1_inverse_value")
        self.horizontalLayout_4.addWidget(self.teta1_inverse_value)
        self.VerticalLayout_teta_Invere.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.teta2_inverse = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.teta2_inverse.setFont(font)
        self.teta2_inverse.setStyleSheet("")
        self.teta2_inverse.setObjectName("teta2_inverse")
        self.horizontalLayout_6.addWidget(self.teta2_inverse)
        self.teta2_inverse_value = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.teta2_inverse_value.setFont(font)
        self.teta2_inverse_value.setStyleSheet("")
        self.teta2_inverse_value.setObjectName("teta2_inverse_value")
        self.horizontalLayout_6.addWidget(self.teta2_inverse_value)
        self.VerticalLayout_teta_Invere.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.teta3_inverse = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.teta3_inverse.setFont(font)
        self.teta3_inverse.setStyleSheet("")
        self.teta3_inverse.setObjectName("teta3_inverse")
        self.horizontalLayout_5.addWidget(self.teta3_inverse)
        self.teta3_inverse_value = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.teta3_inverse_value.setFont(font)
        self.teta3_inverse_value.setStyleSheet("")
        self.teta3_inverse_value.setObjectName("teta3_inverse_value")
        self.horizontalLayout_5.addWidget(self.teta3_inverse_value)
        self.VerticalLayout_teta_Invere.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.teta4_inverse = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.teta4_inverse.setFont(font)
        self.teta4_inverse.setStyleSheet("")
        self.teta4_inverse.setObjectName("teta4_inverse")
        self.horizontalLayout_8.addWidget(self.teta4_inverse)
        self.teta4_inverse_value = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.teta4_inverse_value.setFont(font)
        self.teta4_inverse_value.setStyleSheet("")
        self.teta4_inverse_value.setObjectName("teta4_inverse_value")
        self.horizontalLayout_8.addWidget(self.teta4_inverse_value)
        self.VerticalLayout_teta_Invere.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.teta5_inverse = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.teta5_inverse.setFont(font)
        self.teta5_inverse.setStyleSheet("")
        self.teta5_inverse.setObjectName("teta5_inverse")
        self.horizontalLayout_7.addWidget(self.teta5_inverse)
        self.teta5_invers_value = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.teta5_invers_value.setFont(font)
        self.teta5_invers_value.setStyleSheet("")
        self.teta5_invers_value.setObjectName("teta5_invers_value")
        self.horizontalLayout_7.addWidget(self.teta5_invers_value)
        self.VerticalLayout_teta_Invere.addLayout(self.horizontalLayout_7)
        self.PulsanteInvioPAgina_Inverse = QtWidgets.QPushButton(self.Inverse)
        self.PulsanteInvioPAgina_Inverse.setGeometry(QtCore.QRect(730, 220, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PulsanteInvioPAgina_Inverse.setFont(font)
        self.PulsanteInvioPAgina_Inverse.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0246305, y1:0.602273, x2:1, y2:0, stop:0 rgba(0, 139, 0, 255), stop:0.655172 rgba(255, 255, 255, 255));")
        self.PulsanteInvioPAgina_Inverse.setObjectName("PulsanteInvioPAgina_Inverse")
        self.layoutWidget5 = QtWidgets.QWidget(self.Inverse)
        self.layoutWidget5.setGeometry(QtCore.QRect(70, 40, 121, 241))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Xdes = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.Xdes.setFont(font)
        self.Xdes.setStyleSheet("")
        self.Xdes.setObjectName("Xdes")
        self.horizontalLayout.addWidget(self.Xdes)
        self.Xdes_spin_Box = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Xdes_spin_Box.setFont(font)
        self.Xdes_spin_Box.setStyleSheet("")
        self.Xdes_spin_Box.setObjectName("Xdes_spin_Box")
        self.horizontalLayout.addWidget(self.Xdes_spin_Box)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Ydes = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Ydes.setFont(font)
        self.Ydes.setStyleSheet("")
        self.Ydes.setObjectName("Ydes")
        self.horizontalLayout_2.addWidget(self.Ydes)
        self.Ydes_spin_box = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Ydes_spin_box.setFont(font)
        self.Ydes_spin_box.setStyleSheet("")
        self.Ydes_spin_box.setObjectName("Ydes_spin_box")
        self.horizontalLayout_2.addWidget(self.Ydes_spin_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Zdes = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Zdes.setFont(font)
        self.Zdes.setStyleSheet("")
        self.Zdes.setObjectName("Zdes")
        self.horizontalLayout_3.addWidget(self.Zdes)
        self.Zdes_spin_Box = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Zdes_spin_Box.setFont(font)
        self.Zdes_spin_Box.setStyleSheet("")
        self.Zdes_spin_Box.setObjectName("Zdes_spin_Box")
        self.horizontalLayout_3.addWidget(self.Zdes_spin_Box)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.close3 = QtWidgets.QPushButton(self.Inverse)
        self.close3.setGeometry(QtCore.QRect(810, 290, 81, 32))
        self.close3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.close3.setObjectName("close3")
        self.open3 = QtWidgets.QPushButton(self.Inverse)
        self.open3.setGeometry(QtCore.QRect(700, 290, 81, 32))
        self.open3.setStyleSheet("background-color: rgb(255, 255, 247);")
        self.open3.setObjectName("open3")
        self.layoutWidget6 = QtWidgets.QWidget(self.Inverse)
        self.layoutWidget6.setGeometry(QtCore.QRect(300, 70, 171, 61))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Gomitoalto = QtWidgets.QRadioButton(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Gomitoalto.setFont(font)
        self.Gomitoalto.setStyleSheet("")
        self.Gomitoalto.setObjectName("Gomitoalto")
        self.verticalLayout_3.addWidget(self.Gomitoalto)
        self.Gomitobasso = QtWidgets.QRadioButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gomitobasso.sizePolicy().hasHeightForWidth())
        self.Gomitobasso.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Gomitobasso.setFont(font)
        self.Gomitobasso.setStyleSheet("")
        self.Gomitobasso.setObjectName("Gomitobasso")
        self.verticalLayout_3.addWidget(self.Gomitobasso)
        self.o.addTab(self.Inverse, "")
        self.Setup = QtWidgets.QWidget()
        self.Setup.setObjectName("Setup")
        self.Home = QtWidgets.QPushButton(self.Setup)
        self.Home.setGeometry(QtCore.QRect(760, 170, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Home.setFont(font)
        self.Home.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0246305, y1:0.602273, x2:1, y2:0, stop:0 rgba(0, 139, 0, 255), stop:0.655172 rgba(255, 255, 255, 255));")
        self.Home.setObjectName("Home")
        self.Passi_encoder_scritta_2 = QtWidgets.QLabel(self.Setup)
        self.Passi_encoder_scritta_2.setGeometry(QtCore.QRect(10, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Passi_encoder_scritta_2.setFont(font)
        self.Passi_encoder_scritta_2.setObjectName("Passi_encoder_scritta_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Setup)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 40, 181, 301))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.layoutWidget_2.setFont(font)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.Encoder_home_layout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.Encoder_home_layout.setContentsMargins(0, 0, 0, 0)
        self.Encoder_home_layout.setSpacing(11)
        self.Encoder_home_layout.setObjectName("Encoder_home_layout")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.Step1_direct_2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step1_direct_2.sizePolicy().hasHeightForWidth())
        self.Step1_direct_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Step1_direct_2.setFont(font)
        self.Step1_direct_2.setObjectName("Step1_direct_2")
        self.horizontalLayout_43.addWidget(self.Step1_direct_2)
        self.passi1_direct_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.passi1_direct_2.setFont(font)
        self.passi1_direct_2.setObjectName("passi1_direct_2")
        self.horizontalLayout_43.addWidget(self.passi1_direct_2)
        self.Encoder_home_layout.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.Step2_direct_2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step2_direct_2.sizePolicy().hasHeightForWidth())
        self.Step2_direct_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Step2_direct_2.setFont(font)
        self.Step2_direct_2.setObjectName("Step2_direct_2")
        self.horizontalLayout_44.addWidget(self.Step2_direct_2)
        self.passi1_2_direct_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passi1_2_direct_2.setFont(font)
        self.passi1_2_direct_2.setObjectName("passi1_2_direct_2")
        self.horizontalLayout_44.addWidget(self.passi1_2_direct_2)
        self.Encoder_home_layout.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.Step3_direct_2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step3_direct_2.sizePolicy().hasHeightForWidth())
        self.Step3_direct_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Step3_direct_2.setFont(font)
        self.Step3_direct_2.setObjectName("Step3_direct_2")
        self.horizontalLayout_45.addWidget(self.Step3_direct_2)
        self.passi1_3_direct_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passi1_3_direct_2.setFont(font)
        self.passi1_3_direct_2.setObjectName("passi1_3_direct_2")
        self.horizontalLayout_45.addWidget(self.passi1_3_direct_2)
        self.Encoder_home_layout.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.Step4_direct_2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step4_direct_2.sizePolicy().hasHeightForWidth())
        self.Step4_direct_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Step4_direct_2.setFont(font)
        self.Step4_direct_2.setObjectName("Step4_direct_2")
        self.horizontalLayout_46.addWidget(self.Step4_direct_2)
        self.passi1_4_direct_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passi1_4_direct_2.setFont(font)
        self.passi1_4_direct_2.setObjectName("passi1_4_direct_2")
        self.horizontalLayout_46.addWidget(self.passi1_4_direct_2)
        self.Encoder_home_layout.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.Step5_direct_2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step5_direct_2.sizePolicy().hasHeightForWidth())
        self.Step5_direct_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Step5_direct_2.setFont(font)
        self.Step5_direct_2.setObjectName("Step5_direct_2")
        self.horizontalLayout_47.addWidget(self.Step5_direct_2)
        self.passi1_5_direct_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.passi1_5_direct_2.setFont(font)
        self.passi1_5_direct_2.setObjectName("passi1_5_direct_2")
        self.horizontalLayout_47.addWidget(self.passi1_5_direct_2)
        self.Encoder_home_layout.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.Step6_direct_2 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step6_direct_2.sizePolicy().hasHeightForWidth())
        self.Step6_direct_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Step6_direct_2.setFont(font)
        self.Step6_direct_2.setObjectName("Step6_direct_2")
        self.horizontalLayout_48.addWidget(self.Step6_direct_2)
        self.passi1_6_direct_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passi1_6_direct_2.setFont(font)
        self.passi1_6_direct_2.setObjectName("passi1_6_direct_2")
        self.horizontalLayout_48.addWidget(self.passi1_6_direct_2)
        self.Encoder_home_layout.addLayout(self.horizontalLayout_48)
        self.o.addTab(self.Setup, "")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(800, 20, 141, 141))
        self.image.setStyleSheet("image: url(:/image/Logo-Uni-Tor-Vergata.png_256x256.png);")
        self.image.setText("")
        self.image.setObjectName("image")
        UiClass.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UiClass)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 992, 22))
        self.menubar.setObjectName("menubar")
        UiClass.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UiClass)
        self.statusbar.setObjectName("statusbar")
        UiClass.setStatusBar(self.statusbar)

        self.retranslateUi(UiClass)
        self.o.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UiClass)

    def retranslateUi(self, UiClass):
        _translate = QtCore.QCoreApplication.translate
        UiClass.setWindowTitle(_translate("UiClass", "MainWindow"))
        self.o.setToolTip(_translate("UiClass", "<html><head/><body><p>Direct</p><p><br/></p></body></html>"))
        self.o.setWhatsThis(_translate("UiClass", "<html><head/><body><p>B</p><p><br/></p></body></html>"))
        self.Pulsante_invio_pagina_Basics.setText(_translate("UiClass", "ENTER"))
        self.Passi_encoder_scritta.setText(_translate("UiClass", "Encoder Steps "))
        self.Encoder1_direct.setText(_translate("UiClass", "Encoder n°1"))
        self.Encoder_direct.setText(_translate("UiClass", "Encoder n°2"))
        self.Encoder3_direct.setText(_translate("UiClass", "Encoder n°3"))
        self.Ecoder4_direct.setText(_translate("UiClass", "Encoder n°4"))
        self.Encoder5_direct.setText(_translate("UiClass", "Encoder n°5"))
        self.Encoder6_direct.setText(_translate("UiClass", "Encoder n°6"))
        self.encrease1.setText(_translate("UiClass", "encrease of :"))
        self.encrease_value1.setText(_translate("UiClass", "0"))
        self.encrease2.setText(_translate("UiClass", "encrease of :"))
        self.encrease_value2.setText(_translate("UiClass", "0"))
        self.encrease3.setText(_translate("UiClass", "encrease of :"))
        self.encrease_value3.setText(_translate("UiClass", "0"))
        self.encrease4.setText(_translate("UiClass", "encrease of :"))
        self.encrease_value4.setText(_translate("UiClass", "0"))
        self.encrease5.setText(_translate("UiClass", "encrease of : "))
        self.encrease_value5.setText(_translate("UiClass", "0"))
        self.encrease6.setText(_translate("UiClass", "encrease of : "))
        self.encrease_value6.setText(_translate("UiClass", "0"))
        self.Step1_direct.setText(_translate("UiClass", "Step"))
        self.passi1_direct.setText(_translate("UiClass", "0"))
        self.Step2_direct.setText(_translate("UiClass", "Step"))
        self.passi1_2_direct.setText(_translate("UiClass", "0"))
        self.Step3_direct.setText(_translate("UiClass", "Step"))
        self.passi1_3_direct.setText(_translate("UiClass", "0"))
        self.Step4_direct.setText(_translate("UiClass", "Step"))
        self.passi1_4_direct.setText(_translate("UiClass", "0"))
        self.Step5_direct.setText(_translate("UiClass", "Step"))
        self.passi1_5_direct.setText(_translate("UiClass", "0"))
        self.Step6_direct.setText(_translate("UiClass", "Step"))
        self.passi1_6_direct.setText(_translate("UiClass", "0"))
        self.ma1.setText(_translate("UiClass", "mA:"))
        self.ma1_value.setText(_translate("UiClass", "0"))
        self.ma2.setText(_translate("UiClass", "mA:"))
        self.ma2_value.setText(_translate("UiClass", "0"))
        self.ma3.setText(_translate("UiClass", "mA:"))
        self.ma3_value.setText(_translate("UiClass", "0"))
        self.ma4.setText(_translate("UiClass", "mA:"))
        self.ma4_value.setText(_translate("UiClass", "0"))
        self.ma5.setText(_translate("UiClass", "mA:"))
        self.ma5_value.setText(_translate("UiClass", "0"))
        self.ma6.setText(_translate("UiClass", "mA:"))
        self.ma6_value.setText(_translate("UiClass", "0"))
        self.Open1.setText(_translate("UiClass", "Open"))
        self.Close1.setText(_translate("UiClass", "Close"))
        self.o.setTabText(self.o.indexOf(self.Direct), _translate("UiClass", "Direct  EncoderSteps"))
        self.Angle.setText(_translate("UiClass", "Angle"))
        self.PulsanteInvioPAginaAdvance.setText(_translate("UiClass", "ENTER"))
        self.ma1_direct.setText(_translate("UiClass", "mA:"))
        self.ma1_value1_direct.setText(_translate("UiClass", "0"))
        self.ma2_direct.setText(_translate("UiClass", "mA:"))
        self.ma2_value2_direct.setText(_translate("UiClass", "0"))
        self.ma3_direct.setText(_translate("UiClass", "mA:"))
        self.ma3_value3_direct.setText(_translate("UiClass", "0"))
        self.ma4_direct.setText(_translate("UiClass", "mA:"))
        self.ma4_value4_direct.setText(_translate("UiClass", "0"))
        self.ma5_direct.setText(_translate("UiClass", "mA:"))
        self.ma5_value5_direct.setText(_translate("UiClass", "0"))
        self.ma6_direct.setText(_translate("UiClass", "mA:"))
        self.ma6_value6_direct.setText(_translate("UiClass", "0"))
        self.teta1_dir.setText(_translate("UiClass", "θ1:"))
        self.tetaDir_1value.setText(_translate("UiClass", "0"))
        self.teta2_dir.setText(_translate("UiClass", "θ2:"))
        self.tetaDir_2value.setText(_translate("UiClass", "0"))
        self.teta3_dit.setText(_translate("UiClass", "θ3:"))
        self.tetaDir_3value.setText(_translate("UiClass", "0"))
        self.teta4_dit.setText(_translate("UiClass", "θ4:"))
        self.tetaDir_4value.setText(_translate("UiClass", "0"))
        self.teta5_dir.setText(_translate("UiClass", "θ5:"))
        self.tetaDir_5value.setText(_translate("UiClass", "0"))
        self.teta6_dir.setText(_translate("UiClass", "θ6:"))
        self.tetaDir_6value.setText(_translate("UiClass", "0"))
        self.Angle1_dir.setText(_translate("UiClass", "Angle  θ1:  "))
        self.Angle2_dir.setText(_translate("UiClass", "Angle θ2:  "))
        self.Angle3_dir.setText(_translate("UiClass", "Angle θ3:  "))
        self.Angle4_dir.setText(_translate("UiClass", "Angle θ4:  "))
        self.Angle5_dir.setText(_translate("UiClass", "Angle θ5:  "))
        self.Angle6_dir.setText(_translate("UiClass", "Angle θ6:  "))
        self.encrease1_2.setText(_translate("UiClass", "encrease of :"))
        self.encrease_value1_2.setText(_translate("UiClass", "0"))
        self.encrease2_2.setText(_translate("UiClass", "encrease of :"))
        self.encrease_value2_2.setText(_translate("UiClass", "0"))
        self.encrease3_2.setText(_translate("UiClass", "encrease of :"))
        self.encrease_value3_2.setText(_translate("UiClass", "0"))
        self.encrease4_2.setText(_translate("UiClass", "encrease of :"))
        self.encrease_value4_2.setText(_translate("UiClass", "0"))
        self.encrease5_2.setText(_translate("UiClass", "encrease of : "))
        self.encrease_value5_2.setText(_translate("UiClass", "0"))
        self.encrease6_2.setText(_translate("UiClass", "encrease of : "))
        self.encrease_value6_2.setText(_translate("UiClass", "0"))
        self.alpha_6.setText(_translate("UiClass", "α:"))
        self.beta_4.setText(_translate("UiClass", "β:"))
        self.gamma_3.setText(_translate("UiClass", "γ:"))
        self.delta_3.setText(_translate("UiClass", "δ:"))
        self.open2.setText(_translate("UiClass", "Open"))
        self.close2.setText(_translate("UiClass", "Close"))
        self.o.setTabText(self.o.indexOf(self.Direct_Angular), _translate("UiClass", "Direct  AngularPosition"))
        self.Teta1_inverse.setText(_translate("UiClass", "θ1:  "))
        self.teta1_inverse_value.setText(_translate("UiClass", "0"))
        self.teta2_inverse.setText(_translate("UiClass", "θ2:  "))
        self.teta2_inverse_value.setText(_translate("UiClass", "0"))
        self.teta3_inverse.setText(_translate("UiClass", "θ3:  "))
        self.teta3_inverse_value.setText(_translate("UiClass", "0"))
        self.teta4_inverse.setText(_translate("UiClass", "θ4:  "))
        self.teta4_inverse_value.setText(_translate("UiClass", "0"))
        self.teta5_inverse.setText(_translate("UiClass", "θ5:  "))
        self.teta5_invers_value.setText(_translate("UiClass", "0"))
        self.PulsanteInvioPAgina_Inverse.setText(_translate("UiClass", "ENTER"))
        self.Xdes.setText(_translate("UiClass", "Xdes:"))
        self.Ydes.setText(_translate("UiClass", "Ydes:"))
        self.Zdes.setText(_translate("UiClass", "Zdes:"))
        self.close3.setText(_translate("UiClass", "Close"))
        self.open3.setText(_translate("UiClass", "Open"))
        self.Gomitoalto.setText(_translate("UiClass", "Gomito alto"))
        self.Gomitobasso.setText(_translate("UiClass", "Gomito basso"))
        self.o.setTabText(self.o.indexOf(self.Inverse), _translate("UiClass", "Inverse  Kinematics"))
        self.Home.setText(_translate("UiClass", "HOME"))
        self.Passi_encoder_scritta_2.setText(_translate("UiClass", "Home position"))
        self.Step1_direct_2.setText(_translate("UiClass", "encoder n°1"))
        self.passi1_direct_2.setText(_translate("UiClass", "0"))
        self.Step2_direct_2.setText(_translate("UiClass", "encoder n°2"))
        self.passi1_2_direct_2.setText(_translate("UiClass", "0"))
        self.Step3_direct_2.setText(_translate("UiClass", "encoder n°3"))
        self.passi1_3_direct_2.setText(_translate("UiClass", "0"))
        self.Step4_direct_2.setText(_translate("UiClass", "encoder n°4"))
        self.passi1_4_direct_2.setText(_translate("UiClass", "0"))
        self.Step5_direct_2.setText(_translate("UiClass", "encoder n°5"))
        self.passi1_5_direct_2.setText(_translate("UiClass", "0"))
        self.Step6_direct_2.setText(_translate("UiClass", "encoder n°6"))
        self.passi1_6_direct_2.setText(_translate("UiClass", "0"))
        self.o.setTabText(self.o.indexOf(self.Setup), _translate("UiClass", "Setup"))


import logo